export type Article = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  cover: string;
  author?: string;
  authorTitle?: string;
  published: boolean;
  paragraphs: string[];
};

export const ARTICLES: Article[] = [
  // ── 1 ──
  {
    slug: "como-elegir-un-envase-plastico-para-tu-producto",
    title: "Cómo elegir un envase plástico para tu producto",
    excerpt: "Una guía práctica para comparar formato, resistencia, cierre y aplicación antes de pedir cotizaciones.",
    category: "Guías de compra",
    date: "2026-07-31",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "Elegir un envase empieza por entender el uso final. El producto, la forma de llenado, el transporte y la exposición del envase determinan qué solución conviene buscar.",
      "Para comparar proveedores, prepara una ficha sencilla con capacidad, dimensiones, color, tipo de cierre, cantidades aproximadas y mercado de destino. Esa información reduce iteraciones y hace más comparables las propuestas.",
      "También conviene pedir muestras antes de cerrar una producción. Una muestra permite revisar ergonomía, apilado, compatibilidad con la línea y calidad visual en condiciones reales.",
      "Presta atención al material: PET, HDPE, PP y PVC tienen propiedades distintas de barrera, resistencia química y reciclabilidad. El material correcto depende del contenido y del canal de distribución.",
      "Por último, pregunta por cantidades mínimas, tiempos de entrega y condiciones de recompra. Un buen envase es el que funciona técnicamente y encaja en la operación comercial de tu empresa.",
    ],
  },
  // ── 2 ──
  {
    slug: "que-revisar-en-una-tarima-de-plastico",
    title: "Qué revisar en una tarima de plástico",
    excerpt: "Carga, entradas, medidas y condiciones de uso: los puntos que realmente cambian una decisión industrial.",
    category: "Operación industrial",
    date: "2026-07-29",
    cover: "/category-tarimas.png",
    published: true,
    paragraphs: [
      "Una tarima debe evaluarse con la carga estática y dinámica que tendrá en operación, no solo con una cifra aislada del catálogo.",
      "Revisa las dimensiones, el número de entradas para montacargas, la posibilidad de anidado y la estabilidad cuando se apilan unidades o cajas.",
      "La mejor comparación es una prueba con tu propia mercancía y recorrido. Así se valida el desempeño sin confundir una especificación comercial con una garantía de operación.",
      "Las tarimas de plástico tienen ventajas sobre las de madera en higiene, durabilidad y cumplimiento de normas fitosanitarias para exportación. Sin embargo, su costo inicial es mayor, por lo que conviene calcular el retorno por ciclo de uso.",
    ],
  },
  // ── 3 ──
  {
    slug: "reciclado-plastico-como-comparar-proveedores",
    title: "Reciclado plástico: cómo comparar proveedores",
    excerpt: "Origen, consistencia y aplicación: tres variables para encontrar material reciclado que funcione en tu proceso.",
    category: "Materiales y procesos",
    date: "2026-07-26",
    cover: "/category-reciclado.png",
    published: true,
    paragraphs: [
      "Antes de comparar precios, define el origen del material, el formato de entrega y la aplicación que debe cubrir. Un mismo nombre comercial puede referirse a calidades muy distintas.",
      "Pide información sobre lote, color, humedad, contaminantes y variación entre entregas. La consistencia suele ser más importante que el precio de una sola compra.",
      "Documenta una prueba de entrada y conserva una muestra de referencia. Esto facilita la trazabilidad cuando el material pasa por distintas líneas o proveedores.",
      "El plástico reciclado post-industrial suele ofrecer mayor uniformidad que el post-consumo. Para aplicaciones donde el color y las propiedades mecánicas son críticos, es la opción más predecible.",
    ],
  },
  // ── 4 ──
  {
    slug: "maquinaria-para-transformacion-de-plastico",
    title: "Maquinaria para transformación de plástico",
    excerpt: "Cómo ordenar una búsqueda de maquinaria, refacciones y servicio técnico sin perder tiempo.",
    category: "Maquinaria",
    date: "2026-07-23",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Una búsqueda eficiente comienza por el proceso: inyección, soplado, extrusión, rotomoldeo o una combinación de operaciones.",
      "Después, reúne producción objetivo, ventana de materiales, dimensiones de molde, disponibilidad eléctrica y nivel de automatización deseado.",
      "En equipos usados, solicita historial de mantenimiento, fotografías de zonas críticas y disponibilidad de refacciones. Una visita técnica puede ahorrar más que una diferencia inicial de precio.",
      "Considera también el servicio post-venta. Un proveedor con técnicos en México y stock de refacciones reduce drásticamente los tiempos muertos frente a un equipo importado sin soporte local.",
    ],
  },
  // ── 5 ──
  {
    slug: "publicar-un-anuncio-b2b-que-genere-contactos",
    title: "Cómo publicar un anuncio B2B que genere contactos",
    excerpt: "Una estructura clara ayuda a que compradores y proveedores encuentren rápido lo que necesitan.",
    category: "TodoPlástico",
    date: "2026-07-20",
    cover: "/category-productos.png",
    published: true,
    paragraphs: [
      "Un buen anuncio responde en pocas líneas qué ofreces, para quién es y qué información debe tener una empresa interesada para dar el siguiente paso.",
      "Usa un título específico, describe medidas y aplicaciones, elige la categoría correcta y añade fotografías reales del producto o del proceso.",
      "Los datos de contacto deben mantenerse en la ficha pública de empresa o en el enlace externo. El anuncio queda más limpio y las personas saben dónde continuar la conversación.",
      "Incluye palabras que un comprador buscaría: material, capacidad, medidas, proceso de fabricación y ubicación. Esto mejora la visibilidad del anuncio en buscadores y dentro de TodoPlástico.",
    ],
  },
  // ── 6 ──
  {
    slug: "como-el-color-impacta-la-percepcion-de-tu-producto",
    title: "Cómo el color impacta la percepción de tu producto plástico",
    excerpt: "El color comunica calidad, uso y marca. Entender la ciencia del color te da ventaja competitiva.",
    category: "Color y pigmentos",
    date: "2026-08-01",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El color es la primera variable que un comprador percibe en un producto plástico. Antes de evaluar resistencia o funcionalidad, el ojo ya decidió si el producto luce profesional o genérico.",
      "Los pigmentos y masterbatch permiten reproducir colores exactos con consistencia lote a lote. Un proveedor con laboratorio de igualación, como los que usan espectrofotómetros, puede garantizar un deltaE mínimo entre entregas.",
      "Para productos de exterior, la estabilidad UV del pigmento es tan importante como el tono. Un color que se degrada en semanas destruye la percepción de calidad del producto terminado.",
      "Cuando trabajes con un proveedor de color, envía una muestra física de referencia además de un código Pantone. La resina base afecta el resultado final, y una prueba sobre el material real evita sorpresas en producción.",
      "Los masterbatch blancos y negros representan el mayor volumen del mercado, pero los colores especiales son los que diferencian un producto. Invierte en una formulación correcta desde el inicio: cambiar el color después de lanzar al mercado es más caro que hacerlo bien la primera vez.",
    ],
  },
  // ── 7 ──
  {
    slug: "seo-para-empresas-plasticas-guia-basica",
    title: "SEO básico para empresas de plásticos: cómo aparecer en Google",
    excerpt: "Tu empresa existe en internet solo si Google la encuentra. Esta guía te explica por dónde empezar.",
    category: "Marketing B2B",
    date: "2026-08-02",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "La mayoría de empresas del sector plástico en México no tienen presencia digital optimizada. Esto significa que quien sí la tenga, captura la demanda que ya existe en Google.",
      "El primer paso es tener una ficha de Google Business Profile actualizada con dirección, horario, teléfono y fotos reales de tu planta o productos. Esto es gratuito y te posiciona en búsquedas locales como 'envases de plástico en Guadalajara'.",
      "Publicar tu empresa en directorios B2B como TodoPlástico genera backlinks de calidad y aumenta tu visibilidad. Cada anuncio con buena descripción y categoría correcta es una página más que Google puede indexar a tu favor.",
      "Las palabras clave que más buscan tus clientes potenciales son 'comprar [producto] de plástico', 'proveedor de [producto]' y '[producto] plástico México'. Usa estas frases en tu sitio web, perfiles y anuncios.",
      "No necesitas un sitio web complejo. Una página con tu catálogo, datos de contacto y testimonios de clientes es suficiente para empezar. Lo importante es que exista y que Google la encuentre.",
    ],
  },
  // ── 8 ──
  {
    slug: "optimizar-ciclo-de-inyeccion-5-ajustes-rapidos",
    title: "Optimizar el ciclo de inyección: 5 ajustes rápidos",
    excerpt: "Pequeños cambios en temperatura, presión y enfriamiento que reducen tiempos sin sacrificar calidad.",
    category: "Operación industrial",
    date: "2026-08-03",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Reducir el ciclo de inyección un 10% puede significar miles de piezas adicionales al mes con la misma máquina. El truco es optimizar sin generar defectos.",
      "Primer ajuste: revisa la temperatura del molde. Un enfriamiento más eficiente, no más frío, acorta el ciclo sin deformar la pieza. Utiliza circuitos de agua separados para zonas críticas.",
      "Segundo: la presión de empaque. Muchos procesos usan más presión y más tiempo del necesario. Reduce gradualmente y mide el peso de la pieza: cuando baje fuera de especificación, regresa un paso.",
      "Tercero: la velocidad de inyección. Una velocidad bien perfilada llena el molde sin generar quemaduras ni líneas de flujo. Usa dos o tres perfiles de velocidad en lugar de una sola.",
      "Cuarto y quinto: el tiempo de enfriamiento y la descompresión del husillo. El enfriamiento es el componente más largo del ciclo y suele estar sobredimensionado. Mide la temperatura de la pieza al desmoldar: si está muy por debajo del límite, tienes margen. La descompresión excesiva atrapa aire y alarga el ciclo innecesariamente.",
    ],
  },
  // ── 9 ──
  {
    slug: "como-vender-mas-en-todoplastico",
    title: "Cómo vender más en TodoPlástico: guía para proveedores",
    excerpt: "Estrategias prácticas para que tu perfil y anuncios generen más contactos de calidad.",
    category: "TodoPlástico",
    date: "2026-08-04",
    cover: "/category-productos.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "TodoPlástico es un directorio de descubrimiento: los compradores llegan buscando productos y contactan directamente a las empresas. Tu trabajo es facilitar ese camino.",
      "Completa al 100% tu perfil de empresa: nombre, descripción, ubicación, teléfono, WhatsApp, email y sitio web. Los perfiles completos reciben hasta 3 veces más visitas que los incompletos.",
      "Publica tus 5 anuncios gratuitos con títulos específicos. 'Cubetas de 20 litros grado alimenticio' funciona mejor que 'Cubetas varias'. Incluye medidas, material, capacidad y aplicación.",
      "Las fotos hacen la diferencia. Una foto real de tu producto sobre fondo limpio genera más confianza que una imagen genérica de internet. Sube las 5 fotos permitidas por anuncio.",
      "Revisa tus anuncios cada mes. Actualiza precios, agrega información y responde rápido cuando te contacten. Los proveedores que responden en menos de 24 horas cierran significativamente más ventas.",
      "Comparte el enlace de tu perfil de TodoPlástico en tus redes sociales y tarjeta de presentación. Cada visita externa mejora tu posición en los resultados de búsqueda de la plataforma.",
    ],
  },
  // ── 10 ──
  {
    slug: "masterbatch-vs-pigmento-cuando-usar-cada-uno",
    title: "Masterbatch vs pigmento en polvo: cuándo usar cada uno",
    excerpt: "La forma en que añades color a tu proceso afecta calidad, costo y limpieza de producción.",
    category: "Color y pigmentos",
    date: "2026-08-05",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El masterbatch es pigmento concentrado en un carrier de resina, listo para dosificar. El pigmento en polvo es la materia prima pura. Cada formato tiene su lugar en la cadena de transformación.",
      "El masterbatch es la opción más limpia y fácil de manejar. Se dosifica con equipo gravimétrico o volumétrico, no genera polvo en la planta y ofrece una dispersión consistente. Es ideal para inyección, soplado y extrusión de película.",
      "El pigmento en polvo se usa cuando el transformador tiene equipo de premezclado y busca el costo más bajo por kilo de color. Requiere más control de proceso y limpieza, pero ofrece flexibilidad para formulaciones propias.",
      "Para volúmenes pequeños o colores especiales, el masterbatch permite cambiar de color sin limpiar a fondo la máquina. En producción continua de un solo color, el pigmento en polvo puede ser más económico.",
      "La recomendación general: si no tienes equipo de mezclado especializado, usa masterbatch. Si produces más de 10 toneladas mensuales de un solo color y tienes laboratorio, evalúa el pigmento en polvo con tu proveedor de color.",
    ],
  },
  // ── 11-50: artículos pendientes de redacción ──
  {
    slug: "tipos-de-polietileno-hdpe-ldpe-lldpe",
    title: "Tipos de polietileno: HDPE, LDPE y LLDPE explicados",
    excerpt: "Cada polietileno tiene propiedades distintas. Conocerlas te ayuda a elegir la resina correcta para tu producto.",
    category: "Materiales y procesos",
    date: "2026-08-06",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-reducir-merma-en-extrusion-de-pelicula",
    title: "Cómo reducir merma en extrusión de película",
    excerpt: "Ajustes de proceso y buenas prácticas que disminuyen el desperdicio sin frenar la producción.",
    category: "Operación industrial",
    date: "2026-08-07",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "normas-fitosanitarias-exportacion-tarimas-plasticas",
    title: "Normas fitosanitarias y tarimas plásticas para exportación",
    excerpt: "Por qué las tarimas de plástico simplifican el cumplimiento NIMF-15 en comercio internacional.",
    category: "Operación industrial",
    date: "2026-08-08",
    cover: "/category-tarimas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "whatsapp-business-para-empresas-plasticas",
    title: "WhatsApp Business para empresas de plásticos: cómo usarlo bien",
    excerpt: "Configura catálogo, respuestas rápidas y etiquetas para atender mejor a tus clientes B2B.",
    category: "Marketing B2B",
    date: "2026-08-09",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "que-es-el-indice-de-fluidez-mfi",
    title: "Qué es el índice de fluidez (MFI) y por qué importa",
    excerpt: "El MFI determina cómo se comporta una resina en tu proceso. Aprende a interpretarlo.",
    category: "Materiales y procesos",
    date: "2026-08-10",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-fotografiar-productos-plasticos-para-vender",
    title: "Cómo fotografiar productos plásticos para vender más",
    excerpt: "Tips de iluminación, fondo y ángulo para que tus productos se vean profesionales sin estudio.",
    category: "TodoPlástico",
    date: "2026-08-11",
    cover: "/category-productos.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "diferencias-pvc-rigido-flexible",
    title: "PVC rígido vs PVC flexible: diferencias y aplicaciones",
    excerpt: "Dos materiales del mismo polímero con comportamientos opuestos. Cuándo usar cada uno.",
    category: "Materiales y procesos",
    date: "2026-08-12",
    cover: "/category-tuberia.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "errores-comunes-al-comprar-maquinaria-usada",
    title: "5 errores comunes al comprar maquinaria de plástico usada",
    excerpt: "Lo que no te dicen en la venta y cómo proteger tu inversión antes de cerrar trato.",
    category: "Maquinaria",
    date: "2026-08-13",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "google-business-profile-empresas-industriales",
    title: "Google Business Profile: la herramienta gratuita que tu empresa ignora",
    excerpt: "Aparece en Google Maps y búsquedas locales sin gastar un peso. Guía paso a paso.",
    category: "Marketing B2B",
    date: "2026-08-14",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "aditivos-uv-plasticos-exterior",
    title: "Aditivos UV para plásticos de exterior: lo esencial",
    excerpt: "Sin protección UV, el plástico se degrada en meses. Tipos de estabilizadores y cómo elegir.",
    category: "Color y pigmentos",
    date: "2026-08-15",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "rotomoldeo-ventajas-aplicaciones",
    title: "Rotomoldeo: ventajas, limitaciones y aplicaciones industriales",
    excerpt: "Un proceso subestimado que produce piezas huecas de gran tamaño con inversión en molde accesible.",
    category: "Materiales y procesos",
    date: "2026-08-16",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-escribir-descripcion-empresa-b2b",
    title: "Cómo escribir la descripción de tu empresa B2B para atraer clientes",
    excerpt: "Tu descripción es tu pitch de ventas permanente. Hazla corta, clara y orientada al cliente.",
    category: "Marketing B2B",
    date: "2026-08-17",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "plastico-grado-alimenticio-regulaciones-mexico",
    title: "Plástico grado alimenticio: regulaciones en México",
    excerpt: "NOM y COFEPRIS: qué necesitas saber si fabricas o compras envases para alimentos.",
    category: "Guías de compra",
    date: "2026-08-18",
    cover: "/category-envases.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "termoformado-vs-inyeccion-que-conviene",
    title: "Termoformado vs inyección: qué conviene para tu producto",
    excerpt: "Dos procesos, dos lógicas de costo. Cuándo cada uno es la mejor opción.",
    category: "Materiales y procesos",
    date: "2026-08-19",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "tendencias-plasticos-2026-mexico",
    title: "Tendencias en plásticos para 2026 en México",
    excerpt: "Reciclaje, bioplásticos, automatización y nearshoring: lo que está moviendo al sector.",
    category: "Materiales y procesos",
    date: "2026-08-20",
    cover: "/category-reciclado.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-cotizar-un-molde-de-inyeccion",
    title: "Cómo cotizar un molde de inyección sin sorpresas",
    excerpt: "Qué información dar al moldero, qué preguntar y qué debe incluir una cotización seria.",
    category: "Maquinaria",
    date: "2026-08-21",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "linkedin-para-ventas-b2b-sector-plastico",
    title: "LinkedIn para ventas B2B en el sector plástico",
    excerpt: "Cómo usar LinkedIn para conectar con compradores industriales sin parecer spam.",
    category: "Marketing B2B",
    date: "2026-08-22",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "bolsas-biodegradables-vs-oxodegradables",
    title: "Bolsas biodegradables vs oxodegradables: diferencias reales",
    excerpt: "No todo lo 'verde' es igual. Lo que realmente dice la ciencia sobre cada tecnología.",
    category: "Sustentabilidad",
    date: "2026-08-23",
    cover: "/category-bolsas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "mantenimiento-preventivo-inyectora",
    title: "Mantenimiento preventivo de una inyectora: checklist esencial",
    excerpt: "Un plan de mantenimiento básico que evita paros no programados y extiende la vida del equipo.",
    category: "Maquinaria",
    date: "2026-08-24",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "dispersion-de-color-problemas-soluciones",
    title: "Dispersión de color en plásticos: problemas comunes y soluciones",
    excerpt: "Puntos, rayas y variación de tono: causas técnicas y cómo resolverlas en producción.",
    category: "Color y pigmentos",
    date: "2026-08-25",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "packaging-sustentable-sin-perder-funcionalidad",
    title: "Packaging sustentable sin perder funcionalidad",
    excerpt: "Reducir material, cambiar diseño o usar reciclado: estrategias que funcionan en la práctica.",
    category: "Sustentabilidad",
    date: "2026-08-26",
    cover: "/category-envases.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "ferias-industriales-plasticos-mexico-2026",
    title: "Ferias industriales de plásticos en México 2026",
    excerpt: "Calendario de eventos clave para networking, compra de maquinaria y tendencias del sector.",
    category: "Operación industrial",
    date: "2026-08-27",
    cover: "/category-servicios.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-calcular-costo-pieza-inyectada",
    title: "Cómo calcular el costo de una pieza inyectada",
    excerpt: "Material, ciclo, amortización de molde y overhead: la fórmula práctica paso a paso.",
    category: "Operación industrial",
    date: "2026-08-28",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "email-marketing-b2b-sector-industrial",
    title: "Email marketing B2B para el sector industrial: lo que sí funciona",
    excerpt: "Newsletters cortas, técnicas y regulares. Así se mantiene la presencia sin molestar.",
    category: "Marketing B2B",
    date: "2026-08-29",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "pet-reciclado-rpet-aplicaciones",
    title: "PET reciclado (rPET): aplicaciones y oportunidades en México",
    excerpt: "El rPET crece en demanda. Dónde encontrarlo, qué calidades existen y cómo validar proveedores.",
    category: "Sustentabilidad",
    date: "2026-08-30",
    cover: "/category-reciclado.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "soplado-de-envases-parametros-clave",
    title: "Soplado de envases: parámetros clave del proceso",
    excerpt: "Temperatura, presión de aire, tiempo de enfriamiento y distribución de material.",
    category: "Operación industrial",
    date: "2026-08-31",
    cover: "/category-envases.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "pagina-web-empresa-industrial-minima-viable",
    title: "La página web mínima viable para una empresa industrial",
    excerpt: "No necesitas un sitio complejo. Con estas 5 secciones ya estás compitiendo online.",
    category: "Marketing B2B",
    date: "2026-09-01",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "polipropileno-usos-ventajas-proceso",
    title: "Polipropileno: usos, ventajas y consideraciones de proceso",
    excerpt: "El PP es una de las resinas más versátiles. Conoce sus variantes y aplicaciones industriales.",
    category: "Materiales y procesos",
    date: "2026-09-02",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "cubetas-industriales-guia-compra",
    title: "Cubetas industriales: guía de compra por capacidad y uso",
    excerpt: "Desde 4 hasta 25 litros, grado alimenticio o químico. Cómo elegir la cubeta correcta.",
    category: "Guías de compra",
    date: "2026-09-03",
    cover: "/category-cubetas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "nearshoring-oportunidades-plasticos-mexico",
    title: "Nearshoring: oportunidades para la industria del plástico en México",
    excerpt: "La relocalización de manufactura abre puertas a proveedores mexicanos. Cómo prepararse.",
    category: "Operación industrial",
    date: "2026-09-04",
    cover: "/category-servicios.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "colorimetria-basica-para-transformadores",
    title: "Colorimetría básica para transformadores de plástico",
    excerpt: "DeltaE, espacio CIELAB y tolerancias: lo que necesitas saber para hablar de color con propiedad.",
    category: "Color y pigmentos",
    date: "2026-09-05",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "como-elegir-proveedor-bolsas-plasticas",
    title: "Cómo elegir un proveedor de bolsas plásticas",
    excerpt: "Calibre, material, impresión y cantidades: los criterios que definen una buena compra.",
    category: "Guías de compra",
    date: "2026-09-06",
    cover: "/category-bolsas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "automatizacion-planta-plasticos-por-donde-empezar",
    title: "Automatización en planta de plásticos: por dónde empezar",
    excerpt: "No todo se automatiza a la vez. Identifica los puntos de mayor impacto con menor inversión.",
    category: "Operación industrial",
    date: "2026-09-07",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "redes-sociales-empresas-industriales",
    title: "Redes sociales para empresas industriales: lo que vale la pena",
    excerpt: "No todas las redes sirven para B2B industrial. Enfócate en las que generan contactos reales.",
    category: "Marketing B2B",
    date: "2026-09-08",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "tuberia-pead-vs-pvc-aplicaciones",
    title: "Tubería PEAD vs PVC: cuándo usar cada material",
    excerpt: "Flexibilidad vs rigidez, costo vs durabilidad. Comparación técnica para proyectos reales.",
    category: "Materiales y procesos",
    date: "2026-09-09",
    cover: "/category-tuberia.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "control-calidad-piezas-plasticas",
    title: "Control de calidad en piezas plásticas: lo esencial",
    excerpt: "Dimensiones, peso, color y pruebas funcionales: un sistema básico que funciona.",
    category: "Operación industrial",
    date: "2026-09-10",
    cover: "/category-productos.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "economia-circular-plasticos-practica",
    title: "Economía circular en plásticos: de la teoría a la práctica",
    excerpt: "Cómo implementar circularidad en tu operación: recolección, reproceso y diseño para reciclaje.",
    category: "Sustentabilidad",
    date: "2026-09-11",
    cover: "/category-reciclado.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "catalogo-digital-empresa-plastica",
    title: "Cómo crear un catálogo digital para tu empresa plástica",
    excerpt: "PDF interactivo, página web o marketplace: opciones para digitalizar tu oferta sin gastar de más.",
    category: "Marketing B2B",
    date: "2026-09-12",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: false,
    paragraphs: [],
  },
  {
    slug: "defectos-inyeccion-rechupe-rebaba-lineas",
    title: "Defectos en inyección: rechupe, rebaba y líneas de unión",
    excerpt: "Diagnóstico visual rápido y ajustes de proceso para los defectos más frecuentes.",
    category: "Operación industrial",
    date: "2026-09-13",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "materiales-barrera-envases-plasticos",
    title: "Materiales barrera en envases plásticos: EVOH, nylon y multicapa",
    excerpt: "Cuando el producto necesita protección contra oxígeno, humedad o aromas.",
    category: "Materiales y procesos",
    date: "2026-09-14",
    cover: "/category-envases.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "certificaciones-iso-industria-plastica",
    title: "Certificaciones ISO para la industria plástica: cuáles importan",
    excerpt: "ISO 9001, 14001 y 22000: qué certificar según tu mercado y cómo prepararte.",
    category: "Operación industrial",
    date: "2026-09-15",
    cover: "/category-servicios.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "precios-resinas-plasticas-como-se-determinan",
    title: "Precios de resinas plásticas: cómo se determinan y cómo negociar",
    excerpt: "Petróleo, oferta-demanda y logística: los factores que mueven los precios de tu materia prima.",
    category: "Materiales y procesos",
    date: "2026-09-16",
    cover: "/category-resinas.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "maquila-inyeccion-plastico-mexico",
    title: "Maquila de inyección de plástico en México: cómo encontrar el socio correcto",
    excerpt: "Capacidad, calidad, ubicación y comunicación: los criterios para elegir maquilador.",
    category: "Guías de compra",
    date: "2026-09-17",
    cover: "/category-maquinaria.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "sillas-plasticas-industriales-guia-compra",
    title: "Sillas de plástico para negocio: guía de compra",
    excerpt: "Apilables, con brazos, para exterior o interior. Cómo elegir según uso y volumen.",
    category: "Guías de compra",
    date: "2026-09-18",
    cover: "/category-productos.png",
    published: false,
    paragraphs: [],
  },
  {
    slug: "impresion-sobre-plastico-metodos-comparativa",
    title: "Impresión sobre plástico: serigrafía, tampografía, hot stamping e IML",
    excerpt: "Cada método tiene su rango de costo y calidad. Elige el correcto según tu volumen y producto.",
    category: "Materiales y procesos",
    date: "2026-09-19",
    cover: "/category-productos.png",
    published: false,
    paragraphs: [],
  },
];

export const PUBLISHED_ARTICLES = ARTICLES.filter((a) => a.published);

export function articleBySlug(slug: string) {
  return ARTICLES.find((article) => article.slug === slug && article.published);
}
