export type Article = {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  date: string;
  cover: string;
  author?: string;
  authorTitle?: string;
  published: boolean;
  paragraphs: string[];
};

export const ARTICLES: Article[] = [
  // ── 1 ──
  {
    slug: "como-elegir-un-envase-plastico-para-tu-producto",
    title: "Cómo elegir un envase plástico para tu producto",
    excerpt: "Una guía práctica para comparar formato, resistencia, cierre y aplicación antes de pedir cotizaciones.",
    category: "Guías de compra",
    date: "2026-07-31",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "Elegir un envase empieza por entender el uso final. El producto, la forma de llenado, el transporte y la exposición del envase determinan qué solución conviene buscar.",
      "Para comparar proveedores, prepara una ficha sencilla con capacidad, dimensiones, color, tipo de cierre, cantidades aproximadas y mercado de destino. Esa información reduce iteraciones y hace más comparables las propuestas.",
      "También conviene pedir muestras antes de cerrar una producción. Una muestra permite revisar ergonomía, apilado, compatibilidad con la línea y calidad visual en condiciones reales.",
      "Presta atención al material: PET, HDPE, PP y PVC tienen propiedades distintas de barrera, resistencia química y reciclabilidad. El material correcto depende del contenido y del canal de distribución.",
      "Por último, pregunta por cantidades mínimas, tiempos de entrega y condiciones de recompra. Un buen envase es el que funciona técnicamente y encaja en la operación comercial de tu empresa.",
    ],
  },
  // ── 2 ──
  {
    slug: "que-revisar-en-una-tarima-de-plastico",
    title: "Qué revisar en una tarima de plástico",
    excerpt: "Carga, entradas, medidas y condiciones de uso: los puntos que realmente cambian una decisión industrial.",
    category: "Operación industrial",
    date: "2026-07-29",
    cover: "/category-tarimas.png",
    published: true,
    paragraphs: [
      "Una tarima debe evaluarse con la carga estática y dinámica que tendrá en operación, no solo con una cifra aislada del catálogo.",
      "Revisa las dimensiones, el número de entradas para montacargas, la posibilidad de anidado y la estabilidad cuando se apilan unidades o cajas.",
      "La mejor comparación es una prueba con tu propia mercancía y recorrido. Así se valida el desempeño sin confundir una especificación comercial con una garantía de operación.",
      "Las tarimas de plástico tienen ventajas sobre las de madera en higiene, durabilidad y cumplimiento de normas fitosanitarias para exportación. Sin embargo, su costo inicial es mayor, por lo que conviene calcular el retorno por ciclo de uso.",
    ],
  },
  // ── 3 ──
  {
    slug: "reciclado-plastico-como-comparar-proveedores",
    title: "Reciclado plástico: cómo comparar proveedores",
    excerpt: "Origen, consistencia y aplicación: tres variables para encontrar material reciclado que funcione en tu proceso.",
    category: "Materiales y procesos",
    date: "2026-07-26",
    cover: "/category-reciclado.png",
    published: true,
    paragraphs: [
      "Antes de comparar precios, define el origen del material, el formato de entrega y la aplicación que debe cubrir. Un mismo nombre comercial puede referirse a calidades muy distintas.",
      "Pide información sobre lote, color, humedad, contaminantes y variación entre entregas. La consistencia suele ser más importante que el precio de una sola compra.",
      "Documenta una prueba de entrada y conserva una muestra de referencia. Esto facilita la trazabilidad cuando el material pasa por distintas líneas o proveedores.",
      "El plástico reciclado post-industrial suele ofrecer mayor uniformidad que el post-consumo. Para aplicaciones donde el color y las propiedades mecánicas son críticos, es la opción más predecible.",
    ],
  },
  // ── 4 ──
  {
    slug: "maquinaria-para-transformacion-de-plastico",
    title: "Maquinaria para transformación de plástico",
    excerpt: "Cómo ordenar una búsqueda de maquinaria, refacciones y servicio técnico sin perder tiempo.",
    category: "Maquinaria",
    date: "2026-07-23",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Una búsqueda eficiente comienza por el proceso: inyección, soplado, extrusión, rotomoldeo o una combinación de operaciones.",
      "Después, reúne producción objetivo, ventana de materiales, dimensiones de molde, disponibilidad eléctrica y nivel de automatización deseado.",
      "En equipos usados, solicita historial de mantenimiento, fotografías de zonas críticas y disponibilidad de refacciones. Una visita técnica puede ahorrar más que una diferencia inicial de precio.",
      "Considera también el servicio post-venta. Un proveedor con técnicos en México y stock de refacciones reduce drásticamente los tiempos muertos frente a un equipo importado sin soporte local.",
    ],
  },
  // ── 5 ──
  {
    slug: "publicar-un-anuncio-b2b-que-genere-contactos",
    title: "Cómo publicar un anuncio B2B que genere contactos",
    excerpt: "Una estructura clara ayuda a que compradores y proveedores encuentren rápido lo que necesitan.",
    category: "TodoPlástico",
    date: "2026-07-20",
    cover: "/category-productos.png",
    published: true,
    paragraphs: [
      "Un buen anuncio responde en pocas líneas qué ofreces, para quién es y qué información debe tener una empresa interesada para dar el siguiente paso.",
      "Usa un título específico, describe medidas y aplicaciones, elige la categoría correcta y añade fotografías reales del producto o del proceso.",
      "Los datos de contacto deben mantenerse en la ficha pública de empresa o en el enlace externo. El anuncio queda más limpio y las personas saben dónde continuar la conversación.",
      "Incluye palabras que un comprador buscaría: material, capacidad, medidas, proceso de fabricación y ubicación. Esto mejora la visibilidad del anuncio en buscadores y dentro de TodoPlástico.",
    ],
  },
  // ── 6 ──
  {
    slug: "como-el-color-impacta-la-percepcion-de-tu-producto",
    title: "Cómo el color impacta la percepción de tu producto plástico",
    excerpt: "El color comunica calidad, uso y marca. Entender la ciencia del color te da ventaja competitiva.",
    category: "Color y pigmentos",
    date: "2026-08-01",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El color es la primera variable que un comprador percibe en un producto plástico. Antes de evaluar resistencia o funcionalidad, el ojo ya decidió si el producto luce profesional o genérico.",
      "Los pigmentos y masterbatch permiten reproducir colores exactos con consistencia lote a lote. Un proveedor con laboratorio de igualación, como los que usan espectrofotómetros, puede garantizar un deltaE mínimo entre entregas.",
      "Para productos de exterior, la estabilidad UV del pigmento es tan importante como el tono. Un color que se degrada en semanas destruye la percepción de calidad del producto terminado.",
      "Cuando trabajes con un proveedor de color, envía una muestra física de referencia además de un código Pantone. La resina base afecta el resultado final, y una prueba sobre el material real evita sorpresas en producción.",
      "Los masterbatch blancos y negros representan el mayor volumen del mercado, pero los colores especiales son los que diferencian un producto. Invierte en una formulación correcta desde el inicio: cambiar el color después de lanzar al mercado es más caro que hacerlo bien la primera vez.",
    ],
  },
  // ── 7 ──
  {
    slug: "seo-para-empresas-plasticas-guia-basica",
    title: "SEO básico para empresas de plásticos: cómo aparecer en Google",
    excerpt: "Tu empresa existe en internet solo si Google la encuentra. Esta guía te explica por dónde empezar.",
    category: "Marketing B2B",
    date: "2026-08-02",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "La mayoría de empresas del sector plástico en México no tienen presencia digital optimizada. Esto significa que quien sí la tenga, captura la demanda que ya existe en Google.",
      "El primer paso es tener una ficha de Google Business Profile actualizada con dirección, horario, teléfono y fotos reales de tu planta o productos. Esto es gratuito y te posiciona en búsquedas locales como 'envases de plástico en Guadalajara'.",
      "Publicar tu empresa en directorios B2B como TodoPlástico genera backlinks de calidad y aumenta tu visibilidad. Cada anuncio con buena descripción y categoría correcta es una página más que Google puede indexar a tu favor.",
      "Las palabras clave que más buscan tus clientes potenciales son 'comprar [producto] de plástico', 'proveedor de [producto]' y '[producto] plástico México'. Usa estas frases en tu sitio web, perfiles y anuncios.",
      "No necesitas un sitio web complejo. Una página con tu catálogo, datos de contacto y testimonios de clientes es suficiente para empezar. Lo importante es que exista y que Google la encuentre.",
    ],
  },
  // ── 8 ──
  {
    slug: "optimizar-ciclo-de-inyeccion-5-ajustes-rapidos",
    title: "Optimizar el ciclo de inyección: 5 ajustes rápidos",
    excerpt: "Pequeños cambios en temperatura, presión y enfriamiento que reducen tiempos sin sacrificar calidad.",
    category: "Operación industrial",
    date: "2026-08-03",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Reducir el ciclo de inyección un 10% puede significar miles de piezas adicionales al mes con la misma máquina. El truco es optimizar sin generar defectos.",
      "Primer ajuste: revisa la temperatura del molde. Un enfriamiento más eficiente, no más frío, acorta el ciclo sin deformar la pieza. Utiliza circuitos de agua separados para zonas críticas.",
      "Segundo: la presión de empaque. Muchos procesos usan más presión y más tiempo del necesario. Reduce gradualmente y mide el peso de la pieza: cuando baje fuera de especificación, regresa un paso.",
      "Tercero: la velocidad de inyección. Una velocidad bien perfilada llena el molde sin generar quemaduras ni líneas de flujo. Usa dos o tres perfiles de velocidad en lugar de una sola.",
      "Cuarto y quinto: el tiempo de enfriamiento y la descompresión del husillo. El enfriamiento es el componente más largo del ciclo y suele estar sobredimensionado. Mide la temperatura de la pieza al desmoldar: si está muy por debajo del límite, tienes margen. La descompresión excesiva atrapa aire y alarga el ciclo innecesariamente.",
    ],
  },
  // ── 9 ──
  {
    slug: "como-vender-mas-en-todoplastico",
    title: "Cómo vender más en TodoPlástico: guía para proveedores",
    excerpt: "Estrategias prácticas para que tu perfil y anuncios generen más contactos de calidad.",
    category: "TodoPlástico",
    date: "2026-08-04",
    cover: "/category-productos.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "TodoPlástico es un directorio de descubrimiento: los compradores llegan buscando productos y contactan directamente a las empresas. Tu trabajo es facilitar ese camino.",
      "Completa al 100% tu perfil de empresa: nombre, descripción, ubicación, teléfono, WhatsApp, email y sitio web. Los perfiles completos reciben hasta 3 veces más visitas que los incompletos.",
      "Publica tus 5 anuncios gratuitos con títulos específicos. 'Cubetas de 20 litros grado alimenticio' funciona mejor que 'Cubetas varias'. Incluye medidas, material, capacidad y aplicación.",
      "Las fotos hacen la diferencia. Una foto real de tu producto sobre fondo limpio genera más confianza que una imagen genérica de internet. Sube las 5 fotos permitidas por anuncio.",
      "Revisa tus anuncios cada mes. Actualiza precios, agrega información y responde rápido cuando te contacten. Los proveedores que responden en menos de 24 horas cierran significativamente más ventas.",
      "Comparte el enlace de tu perfil de TodoPlástico en tus redes sociales y tarjeta de presentación. Cada visita externa mejora tu posición en los resultados de búsqueda de la plataforma.",
    ],
  },
  // ── 10 ──
  {
    slug: "masterbatch-vs-pigmento-cuando-usar-cada-uno",
    title: "Masterbatch vs pigmento en polvo: cuándo usar cada uno",
    excerpt: "La forma en que añades color a tu proceso afecta calidad, costo y limpieza de producción.",
    category: "Color y pigmentos",
    date: "2026-08-05",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El masterbatch es pigmento concentrado en un carrier de resina, listo para dosificar. El pigmento en polvo es la materia prima pura. Cada formato tiene su lugar en la cadena de transformación.",
      "El masterbatch es la opción más limpia y fácil de manejar. Se dosifica con equipo gravimétrico o volumétrico, no genera polvo en la planta y ofrece una dispersión consistente. Es ideal para inyección, soplado y extrusión de película.",
      "El pigmento en polvo se usa cuando el transformador tiene equipo de premezclado y busca el costo más bajo por kilo de color. Requiere más control de proceso y limpieza, pero ofrece flexibilidad para formulaciones propias.",
      "Para volúmenes pequeños o colores especiales, el masterbatch permite cambiar de color sin limpiar a fondo la máquina. En producción continua de un solo color, el pigmento en polvo puede ser más económico.",
      "La recomendación general: si no tienes equipo de mezclado especializado, usa masterbatch. Si produces más de 10 toneladas mensuales de un solo color y tienes laboratorio, evalúa el pigmento en polvo con tu proveedor de color.",
    ],
  },
  // ── 11-50: artículos pendientes de redacción ──
  {
    slug: "tipos-de-polietileno-hdpe-ldpe-lldpe",
    title: "Tipos de polietileno: HDPE, LDPE y LLDPE explicados",
    excerpt: "Cada polietileno tiene propiedades distintas. Conocerlas te ayuda a elegir la resina correcta para tu producto.",
    category: "Materiales y procesos",
    date: "2026-08-06",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El polietileno no es un solo material, sino una familia de resinas con densidades y estructuras moleculares distintas. Elegir la variante correcta cambia rigidez, resistencia al impacto y comportamiento en proceso.",
      "El HDPE (alta densidad) es rígido, resistente a químicos y con buena barrera a la humedad. Se usa en tarimas, tambores, envases de detergente y tubería, donde se necesita cuerpo estructural.",
      "El LDPE (baja densidad) es más flexible y transparente, ideal para películas, bolsas y recubrimientos. Su menor punto de fusión facilita el sellado térmico en empaque flexible.",
      "El LLDPE (lineal de baja densidad) combina flexibilidad con mayor resistencia al rasgado y perforación que el LDPE convencional. Es el preferido para película stretch y bolsas de alto desempeño.",
      "Al cotizar con un proveedor, especifica siempre el índice de fluidez y la densidad exacta, no solo el nombre genérico. Dos lotes de 'HDPE' pueden comportarse distinto si difieren en estos parámetros.",
      "Para procesos de reciclado o mezcla, confirma la compatibilidad entre tipos: aunque comparten familia química, HDPE y LDPE no siempre se procesan bien juntos sin afectar las propiedades finales.",
    ],
  },
  {
    slug: "como-reducir-merma-en-extrusion-de-pelicula",
    title: "Cómo reducir merma en extrusión de película",
    excerpt: "Ajustes de proceso y buenas prácticas que disminuyen el desperdicio sin frenar la producción.",
    category: "Operación industrial",
    date: "2026-08-07",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "La merma en extrusión de película suele concentrarse en el arranque de línea, los cambios de calibre y los defectos de espesor. Atacar estos tres puntos reduce el desperdicio más que cualquier ajuste aislado.",
      "Un arranque estandarizado, con secuencia escrita de temperaturas y velocidades, acorta el tiempo hasta que la línea produce material en especificación. Cada minuto de arranque improvisado se traduce en kilos de scrap.",
      "El control de espesor con sensores de barrido evita sobredosificar material 'por seguridad'. Trabajar cerca del límite inferior de tolerancia, sin cruzarlo, ahorra resina en cada metro producido.",
      "La molienda y reincorporación del scrap limpio, en el porcentaje que el proceso tolere, recupera valor que de otra forma se pierde. Es clave llevar un registro de cuánto material reciclado interno se está regresando a la mezcla.",
      "Revisa también el manejo de bobinas: cortes mal alineados, empalmes deficientes y daño por manipulación generan merma después del extrusor, no solo durante el proceso.",
      "Un checklist simple de causas de merma, revisado semanalmente por turno, ayuda a detectar patrones antes de que se conviertan en pérdida constante de material y tiempo de máquina.",
    ],
  },
  {
    slug: "normas-fitosanitarias-exportacion-tarimas-plasticas",
    title: "Normas fitosanitarias y tarimas plásticas para exportación",
    excerpt: "Por qué las tarimas de plástico simplifican el cumplimiento NIMF-15 en comercio internacional.",
    category: "Operación industrial",
    date: "2026-08-08",
    cover: "/category-tarimas.png",
    published: true,
    paragraphs: [
      "La norma NIMF-15 exige que el embalaje de madera usado en comercio internacional esté tratado térmicamente o con bromuro de metilo, y marcado con el sello correspondiente. Muchos exportadores descubren este requisito hasta que un contenedor es retenido en aduana.",
      "Las tarimas de plástico quedan fuera del alcance de la NIMF-15 porque no son un medio de propagación de plagas forestales. Esto elimina el riesgo de rechazo por falta de sello, tratamiento vencido o documentación incompleta.",
      "Para exportadores frecuentes, el ahorro no es solo de cumplimiento: se evita el costo de tarimas de un solo uso, el trámite de certificación y el tiempo de espera por inspección fitosanitaria en destino.",
      "Las tarimas plásticas también resisten mejor la humedad marítima y no absorben contaminantes, lo cual es relevante para exportación de alimentos, farmacéuticos y productos con requisitos de higiene estrictos.",
      "Antes de exportar, confirma con tu agente aduanal los requisitos específicos del país destino, ya que algunas naciones piden certificaciones adicionales incluso para embalaje no forestal.",
      "El costo inicial de una tarima plástica es mayor que una de madera, pero su vida útil de varios años y la eliminación de riesgos aduanales suelen justificar la inversión en operaciones de exportación recurrente.",
    ],
  },
  {
    slug: "whatsapp-business-para-empresas-plasticas",
    title: "WhatsApp Business para empresas de plásticos: cómo usarlo bien",
    excerpt: "Configura catálogo, respuestas rápidas y etiquetas para atender mejor a tus clientes B2B.",
    category: "Marketing B2B",
    date: "2026-08-09",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "WhatsApp Business es, en la práctica, el canal de ventas más usado por compradores industriales en México. Configurarlo bien no toma más de una tarde y mejora directamente la tasa de respuesta.",
      "El catálogo dentro de la app permite subir tus productos con foto, precio de referencia y descripción, sin necesidad de un sitio web. Es el punto de partida más rápido para mostrar tu oferta a un cliente nuevo.",
      "Las respuestas rápidas ahorran tiempo en las preguntas que se repiten: precio por volumen, tiempos de entrega, formas de pago y ubicación de planta. Prepara cinco o seis mensajes predefinidos con esta información.",
      "Las etiquetas de colores ayudan a clasificar conversaciones: cliente nuevo, cotización enviada, pedido en proceso, cliente recurrente. Con esta organización es más fácil dar seguimiento sin perder contactos en el chat general.",
      "Activa el mensaje de ausencia y el mensaje de bienvenida automático. Un comprador que escribe fuera de horario y recibe respuesta inmediata, aunque sea automatizada, percibe una empresa más profesional.",
      "Por último, enlaza tu WhatsApp Business directamente en tu perfil de TodoPlástico y en tus anuncios. Reducir los pasos entre 'ver el producto' y 'escribir al proveedor' es lo que más impacta en la conversión.",
    ],
  },
  {
    slug: "que-es-el-indice-de-fluidez-mfi",
    title: "Qué es el índice de fluidez (MFI) y por qué importa",
    excerpt: "El MFI determina cómo se comporta una resina en tu proceso. Aprende a interpretarlo.",
    category: "Materiales y procesos",
    date: "2026-08-10",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El índice de fluidez, o MFI por sus siglas en inglés, mide cuántos gramos de resina fundida pasan por un orificio estándar en diez minutos, bajo temperatura y peso definidos. Es una fotografía rápida de qué tan 'fluida' es una resina.",
      "Un MFI alto indica una resina más fluida, útil para piezas de pared delgada o moldes con geometrías complejas. Un MFI bajo indica mayor viscosidad, típico de aplicaciones que requieren resistencia mecánica o piezas de pared gruesa.",
      "El proceso de transformación determina el rango de MFI adecuado: inyección suele usar valores más altos que extrusión, porque necesita llenar el molde rápido antes de que el material se enfríe.",
      "Dos resinas con el mismo nombre comercial pero distinto MFI se comportan de forma diferente en máquina: cambian presión de inyección, tiempo de ciclo y hasta la apariencia superficial de la pieza.",
      "Al recibir un lote nuevo, verificar el MFI contra la ficha técnica es una prueba de control de calidad rápida y económica. Una desviación fuera de rango suele anticipar problemas de proceso antes de que aparezcan en la pieza terminada.",
    ],
  },
  {
    slug: "como-fotografiar-productos-plasticos-para-vender",
    title: "Cómo fotografiar productos plásticos para vender más",
    excerpt: "Tips de iluminación, fondo y ángulo para que tus productos se vean profesionales sin estudio.",
    category: "TodoPlástico",
    date: "2026-08-11",
    cover: "/category-productos.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "No necesitas un estudio fotográfico para mostrar bien un producto plástico. Con luz natural indirecta, cerca de una ventana pero sin sol directo, ya se elimina la mayoría de sombras duras y reflejos molestos.",
      "Usa un fondo neutro: una cartulina blanca o gris, o incluso una pared lisa sin decoración. El objetivo es que el ojo del comprador se vaya al producto, no a lo que hay alrededor.",
      "El plástico brillante refleja luz y puede generar puntos blancos que ocultan detalles. Cambia el ángulo de la fuente de luz o usa una tela blanca como difusor improvisado para suavizar el reflejo.",
      "Toma al menos tres ángulos: frontal, de tres cuartos y un detalle cercano de la textura o el cierre. Para productos apilables o con múltiples piezas, incluye una foto que muestre el conjunto completo.",
      "Evita el flash del celular de frente: aplana la imagen y genera sombras duras detrás del producto. Es mejor aumentar la luz ambiente que depender del flash.",
      "Sube las fotos en la orientación y proporción que use TodoPlástico, sin marcas de agua ni logos de otras plataformas. Una imagen limpia y consistente en todos tus anuncios transmite más profesionalismo que una sola foto perfecta.",
    ],
  },
  {
    slug: "diferencias-pvc-rigido-flexible",
    title: "PVC rígido vs PVC flexible: diferencias y aplicaciones",
    excerpt: "Dos materiales del mismo polímero con comportamientos opuestos. Cuándo usar cada uno.",
    category: "Materiales y procesos",
    date: "2026-08-12",
    cover: "/category-tuberia.png",
    published: true,
    paragraphs: [
      "El PVC rígido y el PVC flexible parten del mismo polímero base, pero se diferencian por la cantidad de plastificante que se añade en la formulación. Esa proporción cambia por completo el comportamiento del material.",
      "El PVC rígido, sin plastificante o con muy poco, se usa en tubería, perfiles, láminas y conexiones donde se necesita resistencia estructural y estabilidad dimensional bajo presión.",
      "El PVC flexible incorpora plastificantes que le dan elasticidad y suavidad. Se usa en mangueras, empaques de puertas y ventanas, forros y películas donde el material debe doblarse o adaptarse a una forma.",
      "La resistencia química y a la intemperie varía entre ambas versiones. El PVC rígido tiende a ser más resistente a solventes, mientras que el flexible puede perder plastificante con el tiempo y volverse quebradizo si se expone a temperaturas extremas.",
      "Al comprar, especifica siempre la dureza Shore requerida y la aplicación final. Un mismo proveedor puede ofrecer ambas versiones, pero el proceso de transformación y las herramientas necesarias son distintas para cada una.",
    ],
  },
  {
    slug: "errores-comunes-al-comprar-maquinaria-usada",
    title: "5 errores comunes al comprar maquinaria de plástico usada",
    excerpt: "Lo que no te dicen en la venta y cómo proteger tu inversión antes de cerrar trato.",
    category: "Maquinaria",
    date: "2026-08-13",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Primer error: no pedir historial de mantenimiento. Una máquina sin bitácora puede tener fallas ocultas que solo aparecen después de meses de uso continuo. Exige registros o al menos una entrevista con el operador anterior.",
      "Segundo: no correr una prueba con material real. Ver la máquina encendida no es lo mismo que verla producir tu pieza, con tu molde y tu resina. Una prueba de ciclo completo revela problemas que una inspección visual no muestra.",
      "Tercero: ignorar la disponibilidad de refacciones. Máquinas de marcas descontinuadas o de fabricantes sin representación en México pueden dejarte sin soporte cuando falle una tarjeta electrónica o un componente hidráulico específico.",
      "Cuarto: no verificar el consumo eléctrico contra tu instalación. Una inyectora usada puede requerir una acometida distinta a la que tienes, y ese ajuste eléctrico se vuelve un costo no contemplado en el precio de compra.",
      "Quinto: negociar solo por precio y no por condiciones de entrega. Instalación, capacitación, garantía mínima y tiempo de respuesta ante fallas son parte del trato tanto como el número final en la factura.",
      "Antes de cerrar, contrata una inspección técnica independiente si la inversión es considerable. El costo de la revisión es mínimo comparado con el riesgo de comprar un equipo con problemas estructurales ocultos.",
    ],
  },
  {
    slug: "google-business-profile-empresas-industriales",
    title: "Google Business Profile: la herramienta gratuita que tu empresa ignora",
    excerpt: "Aparece en Google Maps y búsquedas locales sin gastar un peso. Guía paso a paso.",
    category: "Marketing B2B",
    date: "2026-08-14",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "Google Business Profile es gratuito y es, para la mayoría de empresas industriales, la herramienta de marketing digital con mejor retorno posible: cero costo y visibilidad directa en Google Maps y búsquedas locales.",
      "Crear el perfil toma quince minutos. Necesitas nombre exacto de tu empresa, categoría del negocio, dirección física, teléfono, horario y sitio web si lo tienes. Google verifica la dirección con una llamada, mensaje o postal.",
      "Sube al menos diez fotos reales: fachada de la planta, área de producción, productos terminados y equipo. Los perfiles con fotos reciben significativamente más clics que los que solo tienen el logo.",
      "La categoría del negocio determina en qué búsquedas apareces. Si vendes envases plásticos, la categoría debe reflejarlo con precisión; una categoría genérica como 'fábrica' te saca de búsquedas específicas como 'envases de plástico Monterrey'.",
      "Pide reseñas a tus clientes recurrentes. Un perfil con reseñas reales, aunque sean pocas, transmite más confianza que uno vacío, y Google favorece perfiles con actividad constante en su algoritmo local.",
      "Actualiza el perfil cada vez que cambie tu horario, teléfono o dirección. Un dato desactualizado hace que un comprador potencial llegue a un lugar equivocado o llame a un número que ya no existe.",
    ],
  },
  {
    slug: "aditivos-uv-plasticos-exterior",
    title: "Aditivos UV para plásticos de exterior: lo esencial",
    excerpt: "Sin protección UV, el plástico se degrada en meses. Tipos de estabilizadores y cómo elegir.",
    category: "Color y pigmentos",
    date: "2026-08-15",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "La radiación ultravioleta rompe las cadenas moleculares del plástico, causando decoloración, pérdida de brillo y fragilidad. Un producto de exterior sin protección UV puede volverse quebradizo en menos de un año.",
      "Los estabilizadores HALS (aminas estéricas impedidas) son de los más efectivos: capturan los radicales libres generados por la luz solar y frenan la degradación desde el interior del material.",
      "Los absorbentes UV, como los benzotriazoles, funcionan distinto: absorben la radiación antes de que dañe el polímero y la disipan como calor. Muchas formulaciones combinan ambos mecanismos para mayor protección.",
      "El negro de humo es, además de pigmento, uno de los protectores UV más económicos y efectivos que existen. Por eso tantos productos de exterior —tinacos, tuberías, tarimas— se fabrican en color negro cuando la estética lo permite.",
      "Para colores distintos al negro, la formulación debe incluir el paquete de aditivos UV por separado, ya que el pigmento por sí solo no siempre ofrece protección suficiente contra la degradación.",
      "Al comprar producto o materia prima para exterior, pregunta específicamente por el paquete de estabilización UV y, si es posible, por resultados de pruebas de intemperismo acelerado o exposición real en campo.",
    ],
  },
  {
    slug: "rotomoldeo-ventajas-aplicaciones",
    title: "Rotomoldeo: ventajas, limitaciones y aplicaciones industriales",
    excerpt: "Un proceso subestimado que produce piezas huecas de gran tamaño con inversión en molde accesible.",
    category: "Materiales y procesos",
    date: "2026-08-16",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "El rotomoldeo consiste en calentar un molde cerrado que gira en dos ejes mientras el polvo de resina, generalmente polietileno, se funde y recubre la pared interior de forma uniforme. El resultado son piezas huecas sin líneas de unión.",
      "La principal ventaja frente a inyección o soplado es el costo de molde: al no requerir presión, los moldes de rotomoldeo son más económicos y permiten producir piezas de gran tamaño, como tinacos, contenedores y juegos infantiles.",
      "El proceso es lento comparado con inyección: un ciclo puede tomar entre veinte minutos y varias horas según el tamaño de la pieza. Por eso el rotomoldeo conviene para volúmenes bajos o medios, no para producción masiva.",
      "El espesor de pared es más difícil de controlar con precisión que en inyección, y las tolerancias dimensionales son más amplias. Es un proceso ideal cuando la funcionalidad importa más que el detalle fino.",
      "Las aplicaciones típicas incluyen tinacos, tambores, kayaks, juegos infantiles, tanques de combustible y mobiliario urbano. Cualquier pieza hueca de gran volumen es candidata natural para este proceso.",
      "Al cotizar un proyecto de rotomoldeo, considera que el diseño de molde y los ángulos de desmolde son distintos a los de inyección. Trabajar con un moldero especializado en rotomoldeo desde el diseño evita rediseños costosos.",
    ],
  },
  {
    slug: "como-escribir-descripcion-empresa-b2b",
    title: "Cómo escribir la descripción de tu empresa B2B para atraer clientes",
    excerpt: "Tu descripción es tu pitch de ventas permanente. Hazla corta, clara y orientada al cliente.",
    category: "Marketing B2B",
    date: "2026-08-17",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "La descripción de tu empresa es lo primero que lee un comprador después del nombre. Tienes pocas líneas para responder qué haces, para quién y por qué deberían elegirte a ti.",
      "Empieza con lo que produces o distribuyes, en lenguaje directo: 'Fabricamos envases plásticos grado alimenticio para la industria de alimentos y bebidas' comunica más que 'Empresa líder con más de veinte años de experiencia'.",
      "Incluye información concreta que un comprador usa para filtrar: años en el mercado, capacidad de producción, certificaciones, ubicación y tipos de cliente que atiendes. Los números y hechos generan más confianza que los adjetivos.",
      "Evita frases genéricas como 'calidad garantizada' o 'los mejores precios' sin respaldo. Si tienes una certificación ISO, un cliente reconocido o una especialidad técnica, menciónala explícitamente en lugar de una afirmación vaga.",
      "Cierra con una llamada a la acción clara: qué debe hacer el lector si le interesa tu oferta. 'Solicita cotización por WhatsApp' o 'Escríbenos para conocer volúmenes mínimos' funciona mejor que dejar la descripción sin cierre.",
      "Revisa tu descripción cada seis meses. Si cambias de línea de producto, agregas una certificación o entras a un nuevo mercado, tu descripción debe reflejarlo para seguir siendo precisa y relevante.",
    ],
  },
  {
    slug: "plastico-grado-alimenticio-regulaciones-mexico",
    title: "Plástico grado alimenticio: regulaciones en México",
    excerpt: "NOM y COFEPRIS: qué necesitas saber si fabricas o compras envases para alimentos.",
    category: "Guías de compra",
    date: "2026-08-18",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "En México, los envases que estarán en contacto con alimentos deben cumplir con la NOM-051 en materia de etiquetado y con los criterios sanitarios que revisa COFEPRIS para materiales en contacto con alimentos.",
      "No cualquier resina 'grado alimenticio' lo es de forma automática: el término se refiere a que el material y sus aditivos están dentro de los límites permitidos de migración hacia el alimento, algo que debe respaldarse con documentación del fabricante de la resina.",
      "Al comprar envases para tu producto alimenticio, pide al proveedor la carta de garantía o certificado de grado alimenticio de la resina utilizada, no solo del envase terminado. Esta trazabilidad es la que revisan las autoridades sanitarias.",
      "El color y los aditivos también importan: un masterbatch o pigmento usado en un envase alimenticio debe estar formulado específicamente para ese uso. Un colorante industrial genérico puede migrar sustancias no permitidas al contenido.",
      "Para exportación, cada país de destino puede tener su propia regulación (FDA en Estados Unidos, por ejemplo), por lo que un envase aprobado para México no garantiza cumplimiento automático en otro mercado.",
      "Guarda toda la documentación de tus proveedores de envase y resina de forma organizada. En una auditoría sanitaria, la trazabilidad completa del material es tan importante como la calidad física del envase.",
    ],
  },
  {
    slug: "termoformado-vs-inyeccion-que-conviene",
    title: "Termoformado vs inyección: qué conviene para tu producto",
    excerpt: "Dos procesos, dos lógicas de costo. Cuándo cada uno es la mejor opción.",
    category: "Materiales y procesos",
    date: "2026-08-19",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "El termoformado calienta una lámina plástica y la moldea sobre un molde con vacío o presión de aire. La inyección funde resina y la inyecta a presión dentro de un molde cerrado. La diferencia de proceso define cuándo conviene cada uno.",
      "El molde de termoformado es notablemente más económico que uno de inyección, porque no soporta la misma presión. Esto lo hace atractivo para volúmenes bajos o medios, prototipos y productos de gran tamaño como charolas o carcasas.",
      "La inyección tiene un costo de molde alto, pero un costo por pieza muy bajo en volúmenes grandes, gracias a ciclos cortos y alta repetibilidad. Para producción masiva y piezas con detalles finos, la inyección es superior.",
      "En términos de resistencia, las piezas inyectadas suelen tener mejor definición estructural y espesores más uniformes. El termoformado tiende a adelgazar el material en las zonas de mayor estiramiento, lo cual debe considerarse en el diseño.",
      "La regla práctica: si tu volumen anual es bajo o tu pieza es de gran tamaño, evalúa termoformado. Si tu volumen es alto y necesitas piezas complejas o con múltiples inserciones, la inyección amortiza mejor el costo de molde.",
    ],
  },
  {
    slug: "tendencias-plasticos-2026-mexico",
    title: "Tendencias en plásticos para 2026 en México",
    excerpt: "Reciclaje, bioplásticos, automatización y nearshoring: lo que está moviendo al sector.",
    category: "Materiales y procesos",
    date: "2026-08-20",
    cover: "/category-reciclado.png",
    published: true,
    paragraphs: [
      "El contenido reciclado ya no es un extra opcional en muchas licitaciones y marcas grandes: cada vez más compradores piden porcentajes mínimos de material reciclado en sus especificaciones de compra.",
      "El nearshoring sigue trayendo demanda de empaque industrial, tarimas, contenedores y componentes técnicos para las nuevas plantas manufactureras que se instalan en el país, especialmente en el norte y el Bajío.",
      "Los bioplásticos y materiales compostables crecen en nicho, aunque su adopción masiva sigue limitada por costo y por la falta de infraestructura de compostaje industrial en la mayoría de ciudades mexicanas.",
      "La automatización avanza en plantas medianas, no solo en las grandes: robots de picking, sistemas de visión para control de calidad y software de monitoreo de máquina se vuelven accesibles a precios más razonables.",
      "La trazabilidad y la digitalización de la cadena de suministro ganan importancia, impulsadas por clientes que exigen reportes de origen del material y evidencia de cumplimiento ambiental.",
      "Para un transformador mediano, la recomendación práctica es priorizar dos o tres de estas tendencias según su mercado, en lugar de intentar adoptar todas a la vez con recursos limitados.",
    ],
  },
  {
    slug: "como-cotizar-un-molde-de-inyeccion",
    title: "Cómo cotizar un molde de inyección sin sorpresas",
    excerpt: "Qué información dar al moldero, qué preguntar y qué debe incluir una cotización seria.",
    category: "Maquinaria",
    date: "2026-08-21",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Antes de pedir cotización, ten listo un archivo 3D de la pieza, la resina que usarás, el volumen anual estimado y el número de cavidades que necesitas. Sin esta información, cualquier precio es solo un estimado grueso.",
      "Especifica el tipo de acero del molde según la vida útil esperada. Un molde para 10,000 piezas no requiere el mismo acero que uno para producción de varios millones; pedir el acero equivocado infla el costo o compromete la durabilidad.",
      "Pregunta explícitamente qué incluye la cotización: diseño, manufactura, acero, canal caliente o frío, texturizado, pruebas de inyección y ajustes posteriores. Muchas cotizaciones bajas excluyen las pruebas, que después se cobran aparte.",
      "Pide el tiempo de entrega comprometido y las condiciones si se retrasa. Un molde tarda típicamente entre cuatro y doce semanas según complejidad; cualquier oferta muy por debajo de ese rango merece revisión cuidadosa.",
      "Verifica quién es dueño del molde al terminar el pago y dónde quedará almacenado si no produces con ese proveedor de forma continua. Esta cláusula evita conflictos si decides cambiar de maquilador en el futuro.",
      "Por último, pide referencias de moldes similares que el proveedor haya fabricado. Ver piezas reales producidas con sus moldes es la mejor evidencia de calidad antes de comprometer la inversión.",
    ],
  },
  {
    slug: "linkedin-para-ventas-b2b-sector-plastico",
    title: "LinkedIn para ventas B2B en el sector plástico",
    excerpt: "Cómo usar LinkedIn para conectar con compradores industriales sin parecer spam.",
    category: "Marketing B2B",
    date: "2026-08-22",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "LinkedIn es la red donde están los compradores industriales, gerentes de compras y directores de operaciones. A diferencia de otras redes, aquí la gente espera contenido de negocio, no solo entretenimiento.",
      "Optimiza tu perfil personal antes que la página de empresa: foto profesional, puesto claro y un resumen que explique a quién ayudas y con qué. Los compradores investigan a la persona antes de escribirle.",
      "Comparte contenido útil, no solo publicidad de tus productos: casos de uso, procesos de tu planta, certificaciones obtenidas o problemas comunes que resuelves. El contenido educativo genera más conexiones reales que la venta directa.",
      "Al conectar con un prospecto, evita el mensaje de venta inmediato. Una nota breve explicando por qué quieres conectar, sin pedir nada a cambio, tiene mucha mejor tasa de aceptación que un pitch en el primer mensaje.",
      "Participa en grupos y publicaciones de tu industria comentando con criterio técnico. Ser reconocido como alguien que sabe del tema construye más confianza a largo plazo que cualquier anuncio pagado.",
      "Usa LinkedIn como complemento, no reemplazo, de tu perfil en TodoPlástico. Un comprador que te encuentra en la plataforma puede validar tu seriedad revisando tu actividad profesional en LinkedIn antes de contactarte.",
    ],
  },
  {
    slug: "bolsas-biodegradables-vs-oxodegradables",
    title: "Bolsas biodegradables vs oxodegradables: diferencias reales",
    excerpt: "No todo lo 'verde' es igual. Lo que realmente dice la ciencia sobre cada tecnología.",
    category: "Sustentabilidad",
    date: "2026-08-23",
    cover: "/category-bolsas.png",
    published: true,
    paragraphs: [
      "Las bolsas biodegradables están hechas de materiales como PLA o almidón, diseñados para descomponerse en compuestos naturales mediante acción microbiana, generalmente en condiciones de compostaje industrial controlado.",
      "Las bolsas oxodegradables son plástico convencional con un aditivo que acelera la fragmentación por oxidación y luz. El resultado no es descomposición real, sino microplásticos: fragmentos pequeños que persisten en el ambiente.",
      "Esta diferencia es la razón por la que varios países y regulaciones locales han restringido o prohibido las bolsas oxodegradables, mientras que las biodegradables certificadas siguen permitidas bajo ciertos estándares.",
      "Al comprar bolsas 'ecológicas', pide la certificación específica (como compostabilidad industrial bajo normas reconocidas) y no te quedes solo con la etiqueta 'biodegradable', que no siempre está respaldada por evidencia verificable.",
      "Para tu empresa, elegir la tecnología correcta no es solo cumplimiento: es también una decisión de reputación. Vender un producto con una promesa ambiental que no se sostiene puede dañar más la marca que no ofrecer alternativa sustentable.",
      "Si tu mercado no tiene acceso a compostaje industrial, una bolsa reciclable de material convencional bien gestionada puede tener menor impacto real que una biodegradable que termina en un relleno sanitario sin las condiciones para descomponerse.",
    ],
  },
  {
    slug: "mantenimiento-preventivo-inyectora",
    title: "Mantenimiento preventivo de una inyectora: checklist esencial",
    excerpt: "Un plan de mantenimiento básico que evita paros no programados y extiende la vida del equipo.",
    category: "Maquinaria",
    date: "2026-08-24",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Un paro no programado por falta de mantenimiento cuesta mucho más que las horas de servicio preventivo. Un plan básico, seguido con disciplina, es la diferencia entre una máquina que dura quince años y una que falla a los cinco.",
      "Revisión diaria: niveles de aceite hidráulico, fugas visibles, temperatura de operación y ruidos anormales. Este chequeo de cinco minutos, hecho por el operador al inicio del turno, detecta problemas antes de que escalen.",
      "Revisión mensual: filtros de aceite hidráulico, bandas, conexiones eléctricas y calibración de termopares. Un termopar descalibrado genera piezas fuera de especificación sin que la máquina reporte error alguno.",
      "Revisión semestral: análisis de aceite hidráulico, desgaste de husillo y cañón, alineación de platos y estado de las resistencias calefactoras. Estos componentes son los más caros de reemplazar si fallan por desgaste acumulado.",
      "Lleva una bitácora física o digital por máquina. Registrar cada intervención permite identificar patrones de falla recurrente y planear el reemplazo de componentes antes de que causen un paro de producción.",
      "Capacita a los operadores para que reporten anomalías de inmediato, no solo cuando la máquina se detiene. Un cambio sutil en el sonido o la vibración suele ser la primera señal de un problema mayor por venir.",
    ],
  },
  {
    slug: "dispersion-de-color-problemas-soluciones",
    title: "Dispersión de color en plásticos: problemas comunes y soluciones",
    excerpt: "Puntos, rayas y variación de tono: causas técnicas y cómo resolverlas en producción.",
    category: "Color y pigmentos",
    date: "2026-08-25",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "Los puntos de color no dispersados, conocidos como 'specks', suelen originarse por una mala dispersión del pigmento en el carrier del masterbatch o por temperatura insuficiente para fundir por completo el concentrado.",
      "Las rayas o vetas de color aparecen cuando el masterbatch no se mezcla homogéneamente con la resina base. Revisar el sistema de dosificación y aumentar el tiempo o la eficiencia de mezclado en el husillo suele resolver el problema.",
      "La variación de tono lote a lote generalmente indica inconsistencia en el proveedor de color, no en tu proceso. Pide al proveedor su control de calidad por deltaE y compara contra una muestra de referencia física, no solo un código digital.",
      "La temperatura de proceso incorrecta puede degradar ciertos pigmentos orgánicos, causando cambios de tono no relacionados con la dispersión. Verifica que la temperatura de proceso esté dentro del rango que el proveedor de color recomienda para ese pigmento específico.",
      "Un masterbatch de mala calidad con baja concentración de pigmento obliga a dosificar más cantidad para lograr el tono deseado, lo cual además de encarecer el proceso puede alterar las propiedades mecánicas de la pieza final.",
      "Antes de cambiar de proveedor de color por un problema de dispersión, valida primero tu propio proceso: temperatura, tiempo de residencia y sistema de dosificación explican la mayoría de estos defectos.",
    ],
  },
  {
    slug: "packaging-sustentable-sin-perder-funcionalidad",
    title: "Packaging sustentable sin perder funcionalidad",
    excerpt: "Reducir material, cambiar diseño o usar reciclado: estrategias que funcionan en la práctica.",
    category: "Sustentabilidad",
    date: "2026-08-26",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "La estrategia más rentable de packaging sustentable suele ser la más simple: reducir el gramaje del envase sin comprometer su función. Un rediseño de pared que baja 10% el peso ahorra material en cada pieza producida, para siempre.",
      "Incorporar contenido reciclado post-industrial o post-consumo es la segunda palanca más accesible. Empezar con porcentajes bajos (10-20%) permite validar el desempeño sin arriesgar la funcionalidad del envase.",
      "Simplificar la estructura del envase también ayuda: eliminar capas innecesarias, unificar materiales para facilitar el reciclaje y evitar combinaciones difíciles de separar, como PET con etiquetas de PVC que contaminan el reciclaje.",
      "El diseño para reciclaje (design for recycling) considera desde el inicio cómo se separará el envase al final de su vida útil. Tapas del mismo material que el cuerpo, sin metalizados ni adhesivos agresivos, facilitan el reciclaje real.",
      "Comunica los cambios con honestidad. Un envase 'más ligero' o 'con material reciclado' es un mensaje verificable que los compradores valoran más que afirmaciones genéricas de sustentabilidad sin datos concretos detrás.",
      "Antes de rediseñar, valida con tu cliente final que el cambio no afecte la percepción de calidad. Un envase más delgado debe seguir sintiéndose sólido en la mano, o el ahorro de material puede costarte ventas.",
    ],
  },
  {
    slug: "ferias-industriales-plasticos-mexico-2026",
    title: "Ferias industriales de plásticos en México 2026",
    excerpt: "Calendario de eventos clave para networking, compra de maquinaria y tendencias del sector.",
    category: "Operación industrial",
    date: "2026-08-27",
    cover: "/category-servicios.png",
    published: true,
    paragraphs: [
      "Asistir a una feria industrial sigue siendo una de las formas más eficientes de ver maquinaria en operación, comparar proveedores en un solo lugar y detectar tendencias antes de que lleguen a tu proveedor habitual.",
      "Las ferias enfocadas en plásticos y empaque suelen reunir expositores de maquinaria, resinas, moldes, aditivos y servicios de reciclaje bajo un mismo techo, lo cual facilita comparar alternativas técnicas en un solo viaje.",
      "Antes de asistir, define objetivos concretos: ¿buscas cotizar maquinaria, encontrar nuevos proveedores de resina, o solo actualizarte en tendencias? Una visita sin objetivo claro suele desperdiciar el tiempo disponible en el evento.",
      "Agenda citas previas con expositores clave en lugar de improvisar en el pasillo. Los representantes técnicos con agenda de citas suelen dar más tiempo y detalle que en una visita espontánea al stand.",
      "Lleva tarjetas de presentación y, si es posible, tu perfil de TodoPlástico o catálogo digital a la mano. Las conexiones que se hacen en feria se enfrían rápido si no das seguimiento en la semana siguiente al evento.",
      "Después del evento, organiza los contactos obtenidos por prioridad y da seguimiento en los primeros diez días. La mayoría de las oportunidades generadas en feria se pierden por falta de seguimiento oportuno, no por falta de interés inicial.",
    ],
  },
  {
    slug: "como-calcular-costo-pieza-inyectada",
    title: "Cómo calcular el costo de una pieza inyectada",
    excerpt: "Material, ciclo, amortización de molde y overhead: la fórmula práctica paso a paso.",
    category: "Operación industrial",
    date: "2026-08-28",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "El costo de una pieza inyectada tiene cuatro componentes principales: material, tiempo de máquina, amortización de molde y overhead. Ignorar cualquiera de ellos produce una cotización que parece competitiva pero no es rentable.",
      "El costo de material se calcula con el peso de la pieza, incluyendo el colado o bebedero si no se recicla en el proceso, multiplicado por el precio de la resina por kilo. No olvides sumar el costo del masterbatch si el producto lleva color.",
      "El costo de máquina se obtiene dividiendo la tarifa por hora del equipo (que incluye energía, mano de obra y mantenimiento) entre el número de piezas producidas por hora, según el tiempo de ciclo real.",
      "La amortización de molde se reparte entre el volumen total del proyecto. Un molde de 200,000 pesos amortizado en 100,000 piezas agrega 2 pesos por pieza; el mismo molde en un proyecto de un millón de piezas agrega apenas 0.20 pesos.",
      "El overhead cubre administración, ventas, renta y utilidad. Muchas empresas lo calculan como un porcentaje fijo sobre los costos anteriores, típicamente entre 15% y 35% según la estructura de la empresa.",
      "Al cotizar, separa estos componentes en lugar de dar un precio único. Esto te permite negociar con el cliente sobre variables específicas, como reducir el ciclo o ajustar el volumen, en lugar de simplemente bajar el precio total.",
    ],
  },
  {
    slug: "email-marketing-b2b-sector-industrial",
    title: "Email marketing B2B para el sector industrial: lo que sí funciona",
    excerpt: "Newsletters cortas, técnicas y regulares. Así se mantiene la presencia sin molestar.",
    category: "Marketing B2B",
    date: "2026-08-29",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "El email sigue siendo el canal donde los compradores industriales prefieren recibir información técnica: no compite por atención como las redes sociales y queda archivado para consulta posterior.",
      "El error más común es enviar correos de venta directa cada vez. Una newsletter que combina información útil, como cambios en precio de resinas o novedades de producto, con ofertas ocasionales, genera mejor tasa de apertura a largo plazo.",
      "La frecuencia importa más que el volumen de contenido. Un correo corto y útil una vez al mes, enviado consistentemente, funciona mejor que campañas esporádicas de contenido extenso que llegan sin ritmo predecible.",
      "Segmenta tu lista por tipo de cliente cuando sea posible: no todos tus contactos compran los mismos productos. Un correo relevante para el destinatario tiene mucha mejor tasa de respuesta que un envío masivo genérico.",
      "El asunto del correo debe ser específico y directo, evitando lenguaje que active filtros de spam. 'Nuevo lote de HDPE disponible esta semana' funciona mejor que asuntos con mayúsculas excesivas o símbolos de urgencia artificial.",
      "Mide tu tasa de apertura y de clics con la herramienta de email que uses. Si después de varios envíos la tasa no mejora, revisa tanto el contenido como la calidad y actualización de tu lista de contactos.",
    ],
  },
  {
    slug: "pet-reciclado-rpet-aplicaciones",
    title: "PET reciclado (rPET): aplicaciones y oportunidades en México",
    excerpt: "El rPET crece en demanda. Dónde encontrarlo, qué calidades existen y cómo validar proveedores.",
    category: "Sustentabilidad",
    date: "2026-08-30",
    cover: "/category-reciclado.png",
    published: true,
    paragraphs: [
      "México es uno de los países con mayor tasa de reciclaje de PET en América Latina, gracias a una cadena de acopio consolidada. Esto hace que el rPET sea uno de los materiales reciclados más accesibles y consistentes del mercado nacional.",
      "Existen distintas calidades de rPET según su origen: grado botella a botella (el más exigente, con procesos de descontaminación certificados) y grado industrial para fibra, flejes o láminas, con menores requisitos de pureza.",
      "La demanda de rPET grado alimenticio crece impulsada por marcas de bebidas y alimentos que se comprometieron públicamente a incluir contenido reciclado en sus envases. Esto ha elevado el precio del rPET de alta calidad frente al PET virgen.",
      "Para validar un proveedor de rPET, pide certificación de grado alimenticio si aplica, información sobre el proceso de descontaminación y una muestra física para pruebas de proceso antes de comprometer volumen.",
      "El color y la presencia de PVC contaminante son los principales problemas de calidad en rPET de origen mixto. Un proveedor serio debe poder explicar su proceso de separación óptica y control de contaminantes.",
      "Para empresas que buscan diferenciarse por sustentabilidad, incorporar rPET no solo reduce el uso de resina virgen: es también un argumento de venta verificable frente a clientes que exigen evidencia de compromiso ambiental.",
    ],
  },
  {
    slug: "soplado-de-envases-parametros-clave",
    title: "Soplado de envases: parámetros clave del proceso",
    excerpt: "Temperatura, presión de aire, tiempo de enfriamiento y distribución de material.",
    category: "Operación industrial",
    date: "2026-08-31",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "En el soplado de envases, el preform o parison se calienta hasta un punto exacto de plasticidad: muy frío no estira bien, muy caliente adelgaza demasiado las paredes. Este control de temperatura es el parámetro más determinante del proceso.",
      "La presión de aire de soplado debe alcanzarse en el momento correcto del ciclo. Una presión insuficiente o tardía genera envases con distribución de pared irregular y puntos débiles en las esquinas o el fondo.",
      "El tiempo de enfriamiento en el molde afecta directamente la velocidad de producción y la estabilidad dimensional del envase. Enfriar de más alarga el ciclo sin beneficio; enfriar de menos puede deformar el envase al desmoldar.",
      "La distribución de material a lo largo del envase depende del perfil de soplado y, en soplado por extrusión, de la programación del espesor de pared del parison. Zonas como el asa o la base suelen necesitar más material que las paredes rectas.",
      "El control de peso de la botella terminada es la forma más rápida de detectar desviaciones de proceso. Un cambio de peso fuera de tolerancia suele anticipar problemas de resistencia antes de que se noten a simple vista.",
      "Para nuevos productos, correr pruebas de caída y de presión interna sobre el envase terminado valida que los parámetros elegidos realmente cumplan la función, no solo que el envase se vea correcto visualmente.",
    ],
  },
  {
    slug: "pagina-web-empresa-industrial-minima-viable",
    title: "La página web mínima viable para una empresa industrial",
    excerpt: "No necesitas un sitio complejo. Con estas 5 secciones ya estás compitiendo online.",
    category: "Marketing B2B",
    date: "2026-09-01",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "Muchas empresas industriales posponen tener sitio web porque imaginan un proyecto caro y complejo. En realidad, cinco secciones bien hechas son suficientes para empezar a competir en búsquedas online.",
      "Inicio: quién eres, qué produces y para qué industrias, en una frase clara arriba de la página. El visitante debe entender en cinco segundos si tu empresa es relevante para lo que busca.",
      "Productos o catálogo: aunque sea una lista simple con fotos y descripciones breves, es la sección que más tráfico de búsqueda atrae. Cada producto en su propia página mejora tu posicionamiento en Google.",
      "Nosotros: años de experiencia, certificaciones, capacidad de producción y clientes que puedas mencionar. Esta sección construye la confianza que un catálogo por sí solo no genera.",
      "Contacto: teléfono, WhatsApp, email, dirección y un mapa. Entre menos pasos tenga que dar un visitante para contactarte, más consultas recibirás.",
      "Blog o novedades, aunque sea con publicaciones ocasionales: le da a Google contenido fresco para indexar y es donde puedes explicar procesos, certificaciones o casos de uso con más detalle que en el catálogo.",
    ],
  },
  {
    slug: "polipropileno-usos-ventajas-proceso",
    title: "Polipropileno: usos, ventajas y consideraciones de proceso",
    excerpt: "El PP es una de las resinas más versátiles. Conoce sus variantes y aplicaciones industriales.",
    category: "Materiales y procesos",
    date: "2026-09-02",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El polipropileno destaca por su buena resistencia química, bajo peso y resistencia a la fatiga por flexión repetida, lo que lo hace ideal para piezas con bisagras integradas, como tapas y cierres vivos.",
      "Existen dos grandes familias: homopolímero, más rígido y con mejor resistencia térmica, y copolímero (random o block), más flexible y resistente al impacto, especialmente a bajas temperaturas.",
      "El PP se usa ampliamente en envases rígidos, tapas, cajas apilables, componentes automotrices y textiles no tejidos. Su versatilidad de proceso permite inyección, extrusión, soplado y termoformado con la misma resina base.",
      "Una de sus limitaciones es la baja adherencia superficial: pintar o imprimir sobre PP requiere tratamiento previo, como flameado o corona, para que la tinta o el recubrimiento se fijen correctamente.",
      "El PP es reciclable y su reciclado post-industrial mantiene propiedades razonablemente estables, lo que lo convierte en una opción atractiva para empresas que buscan incorporar contenido reciclado sin sacrificar demasiado desempeño.",
      "Al comprar PP, especifica el índice de fluidez y si necesitas grado homopolímero o copolímero según tu aplicación. Confundir ambas variantes es un error común que genera piezas quebradizas o demasiado flexibles para el uso previsto.",
    ],
  },
  {
    slug: "cubetas-industriales-guia-compra",
    title: "Cubetas industriales: guía de compra por capacidad y uso",
    excerpt: "Desde 4 hasta 25 litros, grado alimenticio o químico. Cómo elegir la cubeta correcta.",
    category: "Guías de compra",
    date: "2026-09-03",
    cover: "/category-cubetas.png",
    published: true,
    paragraphs: [
      "La capacidad de la cubeta debe definirse por el contenido, no solo por el estándar de la industria. Cubetas de 4, 10, 19 y 25 litros son las más comunes en México, cada una con su propio nicho de uso.",
      "Para contenido alimenticio, exige resina grado alimenticio certificada y verifica que el proveedor pueda mostrar la documentación correspondiente. Esto es indispensable si vas a envasar aceites, conservas o productos para consumo humano.",
      "Para productos químicos, considera la resistencia química del HDPE o PP frente al contenido específico: solventes, ácidos o bases pueden requerir formulaciones distintas o espesores de pared mayores.",
      "El asa metálica o plástica también importa: para cargas pesadas, el asa metálica con soporte plástico distribuye mejor el peso y reduce el riesgo de que se rompa durante el transporte o llenado.",
      "Revisa el sistema de cierre de la tapa: a presión, con anillo de seguridad o roscada. Cada sistema ofrece distinto nivel de hermeticidad, relevante si el contenido es líquido, volátil o sensible a la humedad.",
      "Al cotizar volumen, pregunta por el peso exacto de la cubeta vacía. Una diferencia de pocos gramos por unidad, multiplicada por miles de piezas, representa un ahorro o sobrecosto significativo en el proyecto.",
    ],
  },
  {
    slug: "nearshoring-oportunidades-plasticos-mexico",
    title: "Nearshoring: oportunidades para la industria del plástico en México",
    excerpt: "La relocalización de manufactura abre puertas a proveedores mexicanos. Cómo prepararse.",
    category: "Operación industrial",
    date: "2026-09-04",
    cover: "/category-servicios.png",
    published: true,
    paragraphs: [
      "El nearshoring está atrayendo plantas manufactureras de sectores como automotriz, electrónica y electrodomésticos a México, y cada una de esas plantas necesita proveedores locales de componentes, empaque y servicios plásticos.",
      "Las empresas que se instalan buscan proveedores certificados, con capacidad de respuesta rápida y procesos documentados. Esto empuja a los transformadores mexicanos a formalizar su calidad si quieren participar en estas cadenas de suministro.",
      "La cercanía geográfica es tu ventaja competitiva frente a proveedores asiáticos: menores tiempos de entrega, menor inventario en tránsito y capacidad de ajuste rápido ante cambios de pedido son argumentos que debes destacar activamente.",
      "Prepararte implica revisar tu capacidad instalada real, tus certificaciones vigentes (ISO 9001 es de las más solicitadas) y tu disposición para cumplir auditorías de proveedor, que las empresas trasnacionales suelen exigir antes de firmar contrato.",
      "El idioma y la documentación técnica en inglés también son relevantes: muchas de estas empresas operan con equipos binacionales y valoran proveedores que puedan comunicarse y documentar en ambos idiomas.",
      "Aparecer en directorios B2B como TodoPlástico con información completa aumenta tu visibilidad ante compradores que están mapeando proveedores locales por primera vez, antes de establecer relaciones comerciales formales.",
    ],
  },
  {
    slug: "colorimetria-basica-para-transformadores",
    title: "Colorimetría básica para transformadores de plástico",
    excerpt: "DeltaE, espacio CIELAB y tolerancias: lo que necesitas saber para hablar de color con propiedad.",
    category: "Color y pigmentos",
    date: "2026-09-05",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El espacio de color CIELAB describe cualquier color con tres valores: L para luminosidad, a para el eje verde-rojo y b para el eje azul-amarillo. Es el sistema estándar que usan los espectrofotómetros para medir color de forma objetiva.",
      "El deltaE es la diferencia numérica entre dos colores medidos en CIELAB. Cuanto más bajo el deltaE, más parecidos son los colores; un deltaE por debajo de 1 es prácticamente imperceptible al ojo humano.",
      "Cada aplicación tiene una tolerancia de deltaE distinta. Para producto de consumo visible, un deltaE de 1 a 1.5 suele ser aceptable; para componentes internos donde el color no es crítico, tolerancias más amplias no generan problema.",
      "Un espectrofotómetro portátil es una inversión razonable para cualquier transformador que trabaje con color de forma recurrente. Permite verificar cada lote contra un estándar sin depender solo de la apreciación visual del operador.",
      "La luz bajo la que se observa un color también importa: dos muestras pueden verse iguales bajo luz de oficina y distintas bajo luz solar, un fenómeno llamado metamerismo. Pide siempre revisar el color bajo la iluminación donde el producto final se usará.",
      "Hablar con tu proveedor de color en términos de deltaE y tolerancias numéricas, en lugar de 'se ve parecido', profesionaliza la conversación y reduce discrepancias sobre qué constituye un lote aceptable o rechazado.",
    ],
  },
  {
    slug: "como-elegir-proveedor-bolsas-plasticas",
    title: "Cómo elegir un proveedor de bolsas plásticas",
    excerpt: "Calibre, material, impresión y cantidades: los criterios que definen una buena compra.",
    category: "Guías de compra",
    date: "2026-09-06",
    cover: "/category-bolsas.png",
    published: true,
    paragraphs: [
      "El calibre de la bolsa, medido en micras o en el sistema de calibre local, determina su resistencia. Confirma con el proveedor el calibre exacto y no solo una descripción como 'bolsa gruesa', que varía de interpretación entre fabricantes.",
      "El material cambia el comportamiento: LDPE para bolsas flexibles y transparentes, HDPE para bolsas más económicas y crujientes, y LLDPE para mayor resistencia al rasgado en el mismo calibre.",
      "Si necesitas impresión, define con anticipación el número de colores, la resolución del diseño y si requieres flexografía o algún otro método. Más colores y mayor detalle elevan tanto el costo como el tiempo de entrega.",
      "Las cantidades mínimas varían mucho entre proveedores según si producen bolsa estándar de inventario o bolsa a medida con impresión. Pregunta explícitamente por el mínimo de producción, no solo por el precio unitario a distintos volúmenes.",
      "Pide una muestra física antes de comprometer un pedido grande, especialmente si es la primera vez que trabajas con ese proveedor. La sensación al tacto y la resistencia real solo se validan con producto físico en mano.",
      "Si tu bolsa tiene un uso específico (alimentos, basura industrial, empaque de producto pesado), verifica que el proveedor entienda esa aplicación y no solo venda bolsa genérica sin considerar el esfuerzo mecánico que soportará.",
    ],
  },
  {
    slug: "automatizacion-planta-plasticos-por-donde-empezar",
    title: "Automatización en planta de plásticos: por dónde empezar",
    excerpt: "No todo se automatiza a la vez. Identifica los puntos de mayor impacto con menor inversión.",
    category: "Operación industrial",
    date: "2026-09-07",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Automatizar toda la planta de una vez es costoso y arriesgado. La estrategia más efectiva es identificar el cuello de botella o la tarea más repetitiva y automatizar ahí primero, midiendo el resultado antes de expandir.",
      "El retiro de pieza con robot cartesiano suele ser el primer paso más común en inyección: reduce el tiempo de ciclo al eliminar la espera del operador y mejora la consistencia del retiro, especialmente en piezas delicadas.",
      "El conteo y empaque automatizado libera personal de tareas repetitivas de bajo valor agregado, permitiendo reasignarlo a control de calidad o supervisión de proceso, donde el criterio humano sigue siendo más valioso.",
      "Los sistemas de visión artificial para inspección de defectos son cada vez más accesibles y permiten detectar rechupe, rebaba o variación de color de forma más consistente que una inspección visual humana en turnos largos.",
      "Antes de invertir, calcula el retorno con datos reales de tu planta: horas de mano de obra ahorradas, reducción de scrap y aumento de producción. Una automatización sin caso de negocio claro rara vez se paga en un plazo razonable.",
      "Empieza con un proyecto piloto en una sola línea o célula de trabajo. Los aprendizajes de esa primera automatización, buenos y malos, hacen mucho más eficiente y menos riesgosa la siguiente inversión.",
    ],
  },
  {
    slug: "redes-sociales-empresas-industriales",
    title: "Redes sociales para empresas industriales: lo que vale la pena",
    excerpt: "No todas las redes sirven para B2B industrial. Enfócate en las que generan contactos reales.",
    category: "Marketing B2B",
    date: "2026-09-08",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "No todas las redes sociales generan retorno para una empresa industrial B2B. Antes de invertir tiempo, identifica dónde realmente están tus compradores y qué tipo de contenido consumen ahí.",
      "LinkedIn es la más efectiva para conectar con tomadores de decisión: gerentes de compras, directores de operaciones y dueños de empresa. El contenido técnico y los casos de éxito funcionan mejor que la promoción directa.",
      "Facebook conserva utilidad para negocios que venden también a pequeños compradores o distribuidores locales, especialmente a través de grupos de compraventa industrial regionales donde se comparten oportunidades constantemente.",
      "Instagram funciona si tu producto es visualmente atractivo: procesos de fabricación, productos terminados con buen acabado o antes y después. Para maquinaria pesada o materia prima genérica, el retorno suele ser menor.",
      "No necesitas estar en todas las redes. Es mejor mantener activa una sola plataforma con publicaciones consistentes que tener perfiles abandonados en cinco redes distintas, lo cual transmite descuido más que presencia digital.",
      "Mide resultados con métricas simples: mensajes recibidos, solicitudes de cotización y tráfico hacia tu perfil de TodoPlástico o sitio web. Los likes y seguidores importan menos que los contactos comerciales reales generados.",
    ],
  },
  {
    slug: "tuberia-pead-vs-pvc-aplicaciones",
    title: "Tubería PEAD vs PVC: cuándo usar cada material",
    excerpt: "Flexibilidad vs rigidez, costo vs durabilidad. Comparación técnica para proyectos reales.",
    category: "Materiales y procesos",
    date: "2026-09-09",
    cover: "/category-tuberia.png",
    published: true,
    paragraphs: [
      "La tubería de PEAD (polietileno de alta densidad) es flexible, se suelda por termofusión creando uniones sin fugas, y resiste bien los movimientos de terreno. Es la opción preferida para redes de agua a presión y proyectos con terreno inestable.",
      "La tubería de PVC es más rígida, económica por metro lineal y fácil de instalar con pegamento o cople, pero sus uniones son un punto de vulnerabilidad frente a movimientos de tierra o presión excesiva si no se instalan correctamente.",
      "En resistencia química, el PVC tiene ventaja frente a ciertos solventes, mientras que el PEAD resiste mejor los golpes y la fatiga por presión cíclica, relevante en líneas de bombeo con variaciones frecuentes de presión.",
      "Para proyectos de drenaje sin presión, ambos materiales funcionan bien y la decisión suele basarse en costo y disponibilidad local. Para líneas de agua potable a presión en terrenos con riesgo sísmico, el PEAD ofrece mayor seguridad.",
      "La vida útil de ambos materiales, bien instalados, supera los cincuenta años. La diferencia real está en el método de instalación y en qué tan bien se adapta cada uno a las condiciones específicas del proyecto.",
      "Al cotizar, pide siempre la clasificación de presión (RD o cédula) adecuada para tu aplicación, ya que usar tubería de menor especificación por ahorro inicial puede generar fallas costosas a mediano plazo.",
    ],
  },
  {
    slug: "control-calidad-piezas-plasticas",
    title: "Control de calidad en piezas plásticas: lo esencial",
    excerpt: "Dimensiones, peso, color y pruebas funcionales: un sistema básico que funciona.",
    category: "Operación industrial",
    date: "2026-09-10",
    cover: "/category-productos.png",
    published: true,
    paragraphs: [
      "Un sistema de control de calidad no necesita ser complejo para ser efectivo. Cuatro verificaciones básicas —dimensiones, peso, color y prueba funcional— cubren la mayoría de defectos críticos en piezas plásticas.",
      "El control dimensional con calibrador o gauge específico detecta deformaciones por enfriamiento incorrecto o desgaste de molde. Define los puntos críticos de medición desde el diseño de la pieza, no después de detectar un problema.",
      "El peso de la pieza es un indicador indirecto muy confiable: una desviación de peso suele anticipar problemas de llenado, presión de empaque o cambios no autorizados en el proceso, antes de que se vean a simple vista.",
      "El control de color, idealmente con espectrofotómetro contra una muestra estándar, evita que variaciones sutiles pasen desapercibidas al ojo humano, especialmente en turnos largos donde la fatiga visual reduce la sensibilidad al detalle.",
      "Las pruebas funcionales dependen de la pieza: ensamble con su contraparte, resistencia a caída, hermeticidad o resistencia a la torsión. Simula el uso real del cliente final, no solo la apariencia del producto.",
      "Documenta cada verificación en una hoja de control simple, por lote y turno. Esta trazabilidad es la que te permite responder con datos concretos cuando un cliente reporta un problema de calidad meses después.",
    ],
  },
  {
    slug: "economia-circular-plasticos-practica",
    title: "Economía circular en plásticos: de la teoría a la práctica",
    excerpt: "Cómo implementar circularidad en tu operación: recolección, reproceso y diseño para reciclaje.",
    category: "Sustentabilidad",
    date: "2026-09-11",
    cover: "/category-reciclado.png",
    published: true,
    paragraphs: [
      "La economía circular en plásticos suena abstracta hasta que se traduce en acciones concretas dentro de una planta: reprocesar tu propio scrap, comprar material reciclado y diseñar productos pensando en su fin de vida.",
      "El primer paso, más accesible que cualquier otro, es reprocesar internamente el scrap limpio de tu propia producción. Es material del que ya conoces el origen y las propiedades, y su reincorporación reduce compra de resina virgen de forma inmediata.",
      "El siguiente nivel es incorporar material reciclado de terceros, post-industrial primero por su mayor consistencia, y post-consumo después conforme ganes experiencia validando calidad y desempeño en tu proceso específico.",
      "El diseño para reciclaje implica decisiones desde el inicio: usar un solo tipo de material por producto cuando sea posible, evitar adhesivos permanentes entre materiales distintos y marcar el tipo de resina en piezas grandes.",
      "Cerrar el ciclo también requiere pensar en la recolección: acuerdos con tus propios clientes para recuperar producto al final de su vida útil, o alianzas con centros de acopio, generan un flujo de material reciclado más predecible.",
      "La economía circular no se implementa toda de una vez. Empieza con el scrap propio, mide el ahorro real, y avanza gradualmente hacia reciclado externo y rediseño de producto conforme el retorno de cada paso se confirme.",
    ],
  },
  {
    slug: "catalogo-digital-empresa-plastica",
    title: "Cómo crear un catálogo digital para tu empresa plástica",
    excerpt: "PDF interactivo, página web o marketplace: opciones para digitalizar tu oferta sin gastar de más.",
    category: "Marketing B2B",
    date: "2026-09-12",
    cover: "/category-servicios.png",
    author: "Samuel García",
    authorTitle: "SEO en WF-Studio",
    published: true,
    paragraphs: [
      "Un catálogo digital no requiere gran inversión para empezar a generar valor. La opción más simple es un PDF bien diseñado, con fotos reales, medidas, materiales y datos de contacto, listo para enviar por WhatsApp o correo.",
      "El PDF tiene una limitación: no lo indexa Google como una página web, así que solo llega a quien ya te contactó. Para captar búsquedas nuevas, necesitas que ese mismo contenido viva también en una página web o directorio.",
      "Publicar tu catálogo como anuncios individuales en TodoPlástico combina ambos beneficios: cada producto queda indexable en buscadores y, a la vez, disponible para compartir el enlace directo con un cliente potencial.",
      "Si decides invertir en sitio web propio, prioriza que cada producto tenga su propia página con URL específica. Esto multiplica tus oportunidades de aparecer en distintas búsquedas frente a tener todo el catálogo en una sola página larga.",
      "Mantén el catálogo actualizado: productos descontinuados, precios vencidos o fotos viejas de instalaciones que ya cambiaste generan desconfianza cuando un comprador nota la inconsistencia entre lo publicado y la realidad.",
      "Combina formatos según tu audiencia: PDF para enviar directo a un cliente que ya cotiza, y presencia digital indexable para captar a quien todavía está buscando proveedor y no te conoce.",
    ],
  },
  {
    slug: "defectos-inyeccion-rechupe-rebaba-lineas",
    title: "Defectos en inyección: rechupe, rebaba y líneas de unión",
    excerpt: "Diagnóstico visual rápido y ajustes de proceso para los defectos más frecuentes.",
    category: "Operación industrial",
    date: "2026-09-13",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "El rechupe (hundimiento superficial) aparece en zonas de mayor espesor, como nervaduras o bosses, cuando el material se contrae al enfriar sin suficiente presión de empaque compensando esa contracción. Aumentar el tiempo o presión de empaque suele corregirlo.",
      "La rebaba ocurre cuando el material escapa por la línea de partición del molde, generalmente por exceso de presión de inyección, fuerza de cierre insuficiente o desgaste en la superficie de cierre del molde.",
      "Las líneas de unión (weld lines) se forman donde dos frentes de flujo de material se encuentran al llenar el molde, típicamente alrededor de un barreno o inserto. Aumentar la temperatura del material y la velocidad de inyección mejora su fusión y reduce su visibilidad.",
      "Antes de ajustar parámetros de máquina, verifica que el molde esté en buen estado: ventilas obstruidas, desgaste en la línea de partición o canales de enfriamiento sucios pueden causar estos mismos defectos sin que el proceso tenga la culpa.",
      "Cambia un parámetro a la vez y documenta el resultado. Ajustar temperatura, presión y velocidad simultáneamente dificulta identificar cuál cambio realmente resolvió el defecto y complica reproducir el ajuste en el futuro.",
      "Cuando el defecto persiste a pesar de los ajustes de proceso, el problema suele estar en el diseño del molde o de la pieza misma —espesores no uniformes, mala ubicación del punto de inyección— y requiere revisión de ingeniería, no solo de proceso.",
    ],
  },
  {
    slug: "materiales-barrera-envases-plasticos",
    title: "Materiales barrera en envases plásticos: EVOH, nylon y multicapa",
    excerpt: "Cuando el producto necesita protección contra oxígeno, humedad o aromas.",
    category: "Materiales y procesos",
    date: "2026-09-14",
    cover: "/category-envases.png",
    published: true,
    paragraphs: [
      "Algunos productos —alimentos sensibles al oxígeno, productos químicos, aromas volátiles— necesitan más protección de la que ofrece una resina convencional de una sola capa. Ahí entran los materiales barrera.",
      "El EVOH (etileno vinil alcohol) ofrece una de las mejores barreras contra el oxígeno del mercado, pero es sensible a la humedad, por lo que casi siempre se usa en estructuras multicapa protegido por otras resinas.",
      "El nylon (poliamida) ofrece buena barrera a gases y resistencia mecánica, usado frecuentemente en empaque de carnes al vacío y productos que requieren tanto protección como resistencia a la perforación.",
      "Las estructuras multicapa combinan distintas resinas en capas delgadas: una capa estructural económica, una capa barrera específica y una capa de sellado, unidas con adhesivos compatibles entre capas.",
      "El costo de un envase multicapa es mayor que uno monomaterial, y su reciclaje es más complejo porque separar las capas no siempre es viable. Esta es una tensión real entre desempeño funcional y sustentabilidad que cada empresa debe evaluar según su producto.",
      "Antes de especificar una estructura barrera, define exactamente qué debe bloquear tu producto (oxígeno, humedad, aroma, luz) y por cuánto tiempo. Sobreespecificar la barrera encarece el envase sin beneficio real para el contenido.",
    ],
  },
  {
    slug: "certificaciones-iso-industria-plastica",
    title: "Certificaciones ISO para la industria plástica: cuáles importan",
    excerpt: "ISO 9001, 14001 y 22000: qué certificar según tu mercado y cómo prepararte.",
    category: "Operación industrial",
    date: "2026-09-15",
    cover: "/category-servicios.png",
    published: true,
    paragraphs: [
      "La ISO 9001 certifica un sistema de gestión de calidad y es la certificación más solicitada por clientes industriales, especialmente en nearshoring y cadenas de suministro automotrices o electrónicas.",
      "La ISO 14001 certifica un sistema de gestión ambiental: manejo de residuos, consumo de agua y energía, y cumplimiento normativo ambiental. Cada vez más licitaciones y clientes corporativos la piden como requisito de entrada.",
      "La ISO 22000, específica para seguridad alimentaria, es relevante si produces envases o componentes que estarán en contacto directo con alimentos, complementando (no sustituyendo) los requisitos sanitarios de COFEPRIS.",
      "Certificarse no es solo un trámite documental: implica formalizar procesos que quizás ya haces de forma informal, documentarlos, entrenar al personal y mantener evidencia de cumplimiento de forma continua, no solo el día de la auditoría.",
      "El costo de certificación incluye la consultoría de implementación, la auditoría del organismo certificador y el mantenimiento anual. Evalúa el retorno según qué tan seguido tus clientes actuales o potenciales la exigen como filtro de compra.",
      "Si no tienes certificación aún, empieza documentando tus procesos actuales de forma ordenada. Esa disciplina interna, aunque no tengas el certificado formal, ya mejora tu control de calidad y te acerca al estándar que la certificación exige.",
    ],
  },
  {
    slug: "precios-resinas-plasticas-como-se-determinan",
    title: "Precios de resinas plásticas: cómo se determinan y cómo negociar",
    excerpt: "Petróleo, oferta-demanda y logística: los factores que mueven los precios de tu materia prima.",
    category: "Materiales y procesos",
    date: "2026-09-16",
    cover: "/category-resinas.png",
    published: true,
    paragraphs: [
      "El precio del petróleo y del gas natural, materias primas base de la mayoría de resinas, es el factor de fondo que mueve los precios a mediano plazo. Sin embargo, no es el único ni siempre el más inmediato.",
      "El balance de oferta y demanda regional pesa mucho en el corto plazo: paros de planta programados o no programados, nueva capacidad instalada que entra al mercado, o picos de demanda estacional mueven el precio incluso con costos de materia prima estables.",
      "La logística y el tipo de cambio afectan directamente el precio en México, donde buena parte de la resina se importa. Fletes marítimos, disponibilidad de contenedores y la paridad peso-dólar pueden mover el precio final tanto como el mercado internacional de la resina.",
      "Para negociar mejor, sigue los índices de precio de resina publicados por fuentes especializadas del sector y compara contra lo que te cotizan tus proveedores. Llegar a la negociación con referencias de mercado cambia la conversación.",
      "Los contratos a plazo con volumen comprometido suelen ofrecer mejores condiciones que las compras spot recurrentes, aunque reducen tu flexibilidad si el mercado baja. Evalúa qué porcentaje de tu consumo conviene fijar y cuánto dejar variable.",
      "Diversificar entre dos o tres proveedores de resina, incluso si compras principalmente a uno, te da una referencia de precio real y margen de negociación cuando el mercado se mueve de forma inesperada.",
    ],
  },
  {
    slug: "maquila-inyeccion-plastico-mexico",
    title: "Maquila de inyección de plástico en México: cómo encontrar el socio correcto",
    excerpt: "Capacidad, calidad, ubicación y comunicación: los criterios para elegir maquilador.",
    category: "Guías de compra",
    date: "2026-09-17",
    cover: "/category-maquinaria.png",
    published: true,
    paragraphs: [
      "Elegir un maquilador de inyección no es solo comparar precio por pieza. Un buen socio de maquila debe tener capacidad de máquina en el rango de toneladas que tu molde requiere, con margen para picos de producción.",
      "Visita la planta antes de comprometer un volumen importante. Ver el orden de la planta, el estado de las máquinas y cómo manejan el control de calidad dice más que cualquier presentación comercial.",
      "Pregunta por su experiencia con tu tipo de producto específico, no solo con inyección en general. Un maquilador con experiencia en piezas técnicas de precisión no necesariamente es el mejor para producto de consumo de alto volumen, y viceversa.",
      "La ubicación importa por logística de molde y materia prima: un maquilador cercano reduce tiempos de traslado si necesitas ajustar el molde o resolver un problema de calidad con visitas frecuentes al inicio del proyecto.",
      "La comunicación durante el arranque de producción es la mejor señal de cómo será la relación a largo plazo. Un maquilador que reporta proactivamente problemas y avances genera más confianza que uno que solo responde cuando le preguntas.",
      "Formaliza por escrito quién es dueño del molde, condiciones de resguardo si dejas de producir con ellos, y los términos de calidad y tiempos de entrega. Esta claridad desde el inicio evita conflictos costosos más adelante.",
    ],
  },
  {
    slug: "sillas-plasticas-industriales-guia-compra",
    title: "Sillas de plástico para negocio: guía de compra",
    excerpt: "Apilables, con brazos, para exterior o interior. Cómo elegir según uso y volumen.",
    category: "Guías de compra",
    date: "2026-09-18",
    cover: "/category-productos.png",
    published: true,
    paragraphs: [
      "Para negocios que necesitan mobiliario en volumen —restaurantes, salones de eventos, escuelas—, la silla apilable es la opción más práctica: permite guardar más sillas en menos espacio y facilita el acomodo entre eventos.",
      "El material define el uso: polipropileno resiste bien la intemperie sin decolorarse rápido si lleva estabilizador UV, mientras que otras resinas más económicas pueden ser suficientes para uso exclusivamente interior.",
      "Verifica la capacidad de peso que declara el fabricante y, si es posible, pide la ficha técnica o una prueba de carga. Una silla que falla por sobrecarga genera un problema de seguridad, no solo de calidad.",
      "Para uso exterior, confirma explícitamente la protección UV del material. Una silla que se ve bien en la muestra pero no tiene aditivo UV adecuado puede decolorarse o volverse quebradiza en pocos meses de exposición solar.",
      "Al comprar en volumen, pide muestra física antes del pedido completo y confirma tiempos de entrega reales, ya que estos productos suelen tener producción por lote y no siempre hay inventario inmediato disponible.",
      "Compara el costo total considerando durabilidad, no solo precio unitario: una silla más resistente que dura el doble de tiempo puede ser más económica a largo plazo que reponer constantemente sillas de menor calidad.",
    ],
  },
  {
    slug: "impresion-sobre-plastico-metodos-comparativa",
    title: "Impresión sobre plástico: serigrafía, tampografía, hot stamping e IML",
    excerpt: "Cada método tiene su rango de costo y calidad. Elige el correcto según tu volumen y producto.",
    category: "Materiales y procesos",
    date: "2026-09-19",
    cover: "/category-productos.png",
    published: true,
    paragraphs: [
      "La serigrafía imprime a través de una malla y es ideal para superficies planas o ligeramente curvas con diseños de colores sólidos. Es económica para volúmenes medios y altos, aunque limitada en superficies muy irregulares.",
      "La tampografía usa un sello de silicón que transfiere tinta desde una placa grabada, lo que le permite imprimir sobre superficies curvas o irregulares que la serigrafía no puede cubrir bien, como logos en tapas o piezas pequeñas.",
      "El hot stamping transfiere una lámina metalizada o de color mediante calor y presión, ideal para acabados premium como dorados o plateados. Tiene buena durabilidad pero es más costoso y limitado a diseños relativamente simples.",
      "El IML (in-mold labeling) inserta una etiqueta impresa dentro del molde antes de inyectar, quedando fusionada con la pieza. Ofrece la mejor durabilidad y calidad gráfica, pero requiere mayor inversión y solo es rentable en volúmenes altos.",
      "La elección correcta depende del volumen, la superficie de la pieza y el presupuesto: bajo volumen y superficie irregular favorece tampografía; alto volumen con gráficos complejos y buena resistencia favorece IML.",
      "Antes de decidir, pide muestras físicas impresas con cada método sobre tu producto real. La resistencia a la abrasión y el acabado final varían más de lo esperado entre métodos, y solo se aprecian con la pieza terminada en mano.",
    ],
  },
];

export const PUBLISHED_ARTICLES = ARTICLES.filter((a) => a.published);

export function articleBySlug(slug: string) {
  return ARTICLES.find((article) => article.slug === slug && article.published);
}
