import type { Company, Product } from "@/lib/types";

export const DEMO_COMPANY: Company = {
  id: "agama-preview",
  ref_code: "TP-0001",
  rfc: null,
  name: "AGAMA Pigmentos y Masterbatch",
  slug: "agama-pigmentos-masterbatch",
  description: "Empresa especializada en soluciones para la industria plástica.",
  location: "Fuengirola · Málaga",
  website: "https://agama.es",
  phone: "+34 952 000 000",
  email: "admin@agama-pigmentos.com",
  whatsapp: "+34 600 000 000",
  categories: ["envases-y-botellas", "tarimas-y-contenedores"],
  logo_url: "/agama-logo.png",
  plan: "pro",
  is_verified: true,
  is_featured: true,
  status: "active",
  accepted_terms_at: null,
  created_at: "2026-08-01T09:00:00.000Z",
};

export const DEMO_LISTINGS: Product[] = [
  {
    id: 2,
    company_id: DEMO_COMPANY.id,
    title: "Tazas de plástico reutilizables 350 ml para eventos",
    slug: "tazas-plastico-reutilizables-350ml-eventos",
    description: "Tazas rígidas reutilizables de 350 ml para eventos, comedores industriales y promociones corporativas.",
    type: "product",
    category: "envases-y-botellas",
    tags: ["tazas", "contenedores"],
    price_mxn: 8.5,
    unit: "unidad",
    min_purchase_qty: 500,
    location: "Ciudad de Mexico",
    contact_override: { method: "email", value: DEMO_COMPANY.email },
    external_url: "https://agama.es",
    status: "published",
    rejection_reason: null,
    expires_at: null,
    created_at: "2026-08-02T09:00:00.000Z",
    updated_at: "2026-08-02T09:00:00.000Z",
    photos: [],
    company: DEMO_COMPANY,
  },
  {
    id: 9002,
    company_id: DEMO_COMPANY.id,
    title: "Contenedores industriales apilables de alta resistencia",
    slug: "contenedores-industriales-apilables-alta-resistencia",
    description: "Cajas y contenedores de plástico para almacenaje y logística industrial.",
    type: "product",
    category: "tarimas-y-contenedores",
    tags: ["contenedores-apilables", "cajas-industriales"],
    price_mxn: 420,
    unit: "unidad",
    min_purchase_qty: 10,
    location: "Fuengirola · Málaga",
    contact_override: { method: "email", value: DEMO_COMPANY.email },
    external_url: "https://agama.es",
    status: "pending_review",
    rejection_reason: null,
    expires_at: null,
    created_at: "2026-08-02T12:00:00.000Z",
    updated_at: "2026-08-02T12:00:00.000Z",
    photos: [],
    company: DEMO_COMPANY,
  },
];
